function k(b,a,c,d,e){b.o.Jb(b.kb,a,c,d,e)}function l(b,a,c,d){b.o.oa?k(b,a,c,d):b.o.Ge()._OnMessageFromDOM({type:"event",component:b.kb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.o.D(b.kb,a,c)}function t(b,a){for(const [c,d]of a)p(b,c,d)}function u(b){b.Tb||(b.o.ze(b.Wd),b.Tb=!0)}function aa(b){b.Tb&&(b.o.Re(b.Wd),b.Tb=!1)}window.Hb=class{constructor(b,a){this.o=b;this.kb=a;this.Tb=!1;this.Wd=()=>this.Da()}ed(){}Da(){}};
function ba(b){-1!==b.Za&&(self.clearTimeout(b.Za),b.Za=-1)}window.we=class{constructor(b){this.Ic=b;this.Ve=5;this.Za=-1;this.Wb=-Infinity;this.Xd=()=>{this.Za=-1;this.Wb=Date.now();this.pb=!0;this.Ic();this.pb=!1};this.zd=this.pb=!1}j(){ba(this);this.Xd=this.Ic=null}};"use strict";
function ca(b,a){const c=a.elementId,d=b.jd(c,a);b.X.set(c,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{v(b,"elem-focused",c)});d.addEventListener("blur",()=>{v(b,"elem-blurred",c)});b.ib&&document.body.appendChild(d)}function w(b,a,c){p(b,a,d=>{const e=b.X.get(d.elementId);return c(e,d)})}function v(b,a,c,d){d||(d={});d.elementId=c;k(b,a,d)}
window.pe=class extends self.Hb{constructor(b){super(b,"video");this.X=new Map;this.ib=!0;t(this,[["create",a=>ca(this,a)],["destroy",a=>{a=a.elementId;const c=this.X.get(a);this.ld(c);this.ib&&c.parentElement.removeChild(c);this.X.delete(a)}],["set-visible",a=>{this.ib&&(this.X.get(a.elementId).style.display=a.isVisible?"":"none")}],["update-position",a=>{if(this.ib){var c=this.X.get(a.elementId);c.style.left=a.left+"px";c.style.top=a.top+"px";c.style.width=a.width+"px";c.style.height=a.height+"px";
a=a.fontSize;null!==a&&(c.style.fontSize=a+"em")}}],["update-state",a=>{this.X.get(a.elementId);this.od()}],["focus",a=>{const c=this.X.get(a.elementId);a.focus?c.focus():c.blur()}],["set-css-style",a=>{const c=this.X.get(a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{this.X.get(a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{this.X.get(a.elementId).removeAttribute(a.name)}]]);w(this,"get-element",a=>a)}jd(){throw Error("required override");
}ld(){}od(){throw Error("required override");}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent);let ea=0;function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.ff?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.kf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
let fa=!1,ha=!1;function ia(){if(!fa){try{new Worker("blob://",{get type(){ha=!0}})}catch(b){}fa=!0}return ha}let A=new Audio;const ja={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};
A=null;async function ka(b){b=await la(b);return(new TextDecoder("utf-8")).decode(b)}function la(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const D=[];let E=0;window.RealFile=window.File;const G=[],ma=new Map,pa=new Map;let qa=0;const ra=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ra.push(b)};const sa=new Set(["cordova","playable-ad","instant-games"]);
let ta=!1;
window.gb=class b{constructor(a){this.oa=a.mf;this.xa=null;this.ca="";this.Xa=a.jf;this.Eb={};this.Qa=this.va=null;this.Rb=[];this.H=this.ya=null;this.Rc=!1;this.Dd=0;this.rb=null;this.Wa=-1;this.$e=()=>this.Ne();this.Va=[];this.B=a.Yd;this.Ub="file"===location.protocol.substr(0,4);!this.oa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ia()||(this.oa=!1);if("playable-ad"===this.B||"instant-games"===this.B)this.oa=!1;if("cordova"===this.B&&this.oa)if(x){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&
90<=parseInt(c[1],10)||(this.oa=!1)}else this.oa=!1;this.Yb=this.sa=null;"html5"!==this.B||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.D("runtime","cordova-fetch-local-file",c=>this.Je(c));this.D("runtime","create-job-worker",()=>this.Ke());"cordova"===this.B?document.addEventListener("deviceready",()=>this.rd(a)):this.rd(a)}j(){this.zc();
this.xa&&(this.xa=this.xa.onmessage=null);this.va&&(this.va.terminate(),this.va=null);this.Qa&&(this.Qa.j(),this.Qa=null);this.H&&(this.H.parentElement.removeChild(this.H),this.H=null)}te(){return da&&"cordova"===this.B}vc(){const a=navigator.userAgent;return da&&sa.has(this.B)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}re(){return x}uc(){return x&&sa.has(this.B)}async rd(a){"macos-wkwebview"===this.B&&this.Se();if("playable-ad"===this.B){this.sa=self.c3_base64files;this.Yb={};await this.Ce();
for(let d=0,e=a.$a.length;d<e;++d){var c=a.$a[d];this.Yb.hasOwnProperty(c)?a.$a[d]={ff:!0,kf:this.Yb[c]}:this.sa.hasOwnProperty(c)&&(a.$a[d]=URL.createObjectURL(this.sa[c]))}}a.hf?this.ca=a.hf:(c=location.origin,this.ca=("null"===c?"file:///":c)+location.pathname,c=this.ca.lastIndexOf("/"),-1!==c&&(this.ca=this.ca.substr(0,c+1)));a.pf&&(this.Eb=a.pf);c=new MessageChannel;this.xa=c.port1;this.xa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>
this.Me(d));this.rb=new self.ue(this);await ua(this.rb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.oa?await this.Ie(a,c.port2):await this.He(a,c.port2)}Bc(a){a=this.Eb.hasOwnProperty(a)?this.Eb[a]:a.endsWith("/workermain.js")&&this.Eb.hasOwnProperty("workermain.js")?this.Eb["workermain.js"]:
"playable-ad"===this.B&&this.sa.hasOwnProperty(a)?this.sa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async pc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.B&&this.Ub)return a=await this.Gb(d.ef?a:this.Xa+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}qa(){return Math.max(window.innerWidth,1)}ja(){return Math.max(window.innerHeight,1)}qd(a){var c=this.ca,d=location.href,e=this.qa(),f=this.ja(),g=window.devicePixelRatio,h=b.eb(),m=a.uf,q=window.cr_previewImageBlobs||this.sa,n=window.cr_previewProjectFileBlobs,B=window.cr_previewProjectFiles,y=window.sf||"";a=a.Yd;var r=(new URLSearchParams(self.location.search)).has("debug"),C=this.rb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,
isFullscreen:h,projectData:m,previewImageBlobs:q,previewProjectFileBlobs:n,previewProjectFileSWUrls:B,swClientId:y,exportType:a,isDebug:r,ife:!!self.tf,jobScheduler:{inputPort:C.Qc,outputPort:C.Yc,maxNumWorkers:C.Xe},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Xa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Xa+"opus.wasm.wasm",isFileProtocol:this.Ub,isiOSCordova:this.te(),isiOSWebView:this.vc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ie(a,
c){const d=this.Bc(a.nf);"preview"===this.B?(this.va=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const q=n=>{this.va.removeEventListener("message",q);n.data&&"ok"===n.data.type?h():m()};this.va.addEventListener("message",q);this.va.postMessage({type:"construct-worker-init","import":(new URL(d,this.ca)).toString()})})):this.va=await this.pc(d,this.ca,{type:"module",name:"Runtime",ef:!0});this.H=document.createElement("canvas");this.H.style.display="none";
const e=this.H.transferControlToOffscreen();document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.dd||[],g=a.$a;f=await Promise.all(f.map(h=>this.La(h)));g=await Promise.all(g.map(h=>this.La(h)));if("cordova"===this.B)for(let h=0,m=a.nc.length;h<m;++h){const q=a.nc[h],n=q[0];if(n===a.bd||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))q[1]=await this.La(n)}this.va.postMessage(Object.assign(this.qd(a),{type:"init-runtime",
isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.nc,mainProjectScript:a.bd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...va(this.rb)]);this.Rb=G.map(h=>new h(this));this.pd();wa(this.ya);self.c3_callFunction=(h,m)=>{var q=this.ya;return q.o.nd(q.kb,"js-invoke-function",{name:h,params:m},void 0,void 0)};"preview"===this.B&&(self.goToLastErrorScript=()=>this.Jb("runtime","go-to-last-error-script"))}async He(a,c){this.H=document.createElement("canvas");
this.H.style.display="none";document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Rb=G.map(g=>new g(this));this.pd();var d=a.$a.map(g=>"string"===typeof g?(new URL(g,this.ca)).toString():g);Array.isArray(a.dd)&&d.unshift(...a.dd);d=await Promise.all(d.map(g=>this.La(g)));await Promise.all(d.map(g=>z(g)));d=self.C3_ProjectScriptsStatus;const e=a.bd,f=a.nc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.La(h),await z(h),"preview"!==
this.B||d[g]||this.td(g,"main script did not run to completion")}catch(m){this.td(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.La(h),await z(h);"preview"===this.B&&"object"!==typeof self.qf.rf?(this.Nb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.qd(a),
{isInWorker:!1,messagePort:c,canvas:this.H,runOnStartupFunctions:ra}),wa(this.ya),this.sd(),this.Qa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Qa,a))}td(a,c){this.Nb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}sd(){this.Nb()}Nb(){const a=window.cf;a&&(a.parentElement.removeChild(a),window.cf=null)}async Ke(){const a=
await xa(this.rb);return{outputPort:a,transferables:[a]}}Ge(){if(this.oa)throw Error("not available in worker mode");return this.Qa}Jb(a,c,d,e,f){this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}nd(a,c,d,e,f){const g=qa++,h=new Promise((m,q)=>{pa.set(g,{resolve:m,reject:q})});this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Le(a);
if("result"===c)this.Oe(a);else if("runtime-ready"===c)this.Pe();else if("alert-error"===c)this.Nb(),alert(a.message);else if("creating-runtime"===c)this.sd();else throw Error(`unknown message '${c}'`);}Le(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=ma.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Mb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Mb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,
h);this.Mb(f,!1,""+h)}):this.Mb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Mb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.xa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Oe(a){const c=a.responseId,d=a.isOk;a=a.result;const e=pa.get(c);d?e.resolve(a):e.reject(a);pa.delete(c)}D(a,c,d){let e=ma.get(a);e||(e=new Map,ma.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);
e.set(c,d)}static Fb(a){if(G.includes(a))throw Error("DOM handler already added");G.push(a)}pd(){for(const a of this.Rb)if("runtime"===a.kb){this.ya=a;return}throw Error("cannot find runtime DOM handler");}Me(a){this.Jb("debugger","message",a)}Pe(){for(const a of this.Rb)a.ed()}static eb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ta)}static ud(a){ta=!!a}ze(a){this.Va.push(a);this.Gc()}Re(a){a=this.Va.indexOf(a);if(-1===a)throw Error("invalid callback");
this.Va.splice(a,1);this.Va.length||this.zc()}Gc(){-1===this.Wa&&this.Va.length&&(this.Wa=requestAnimationFrame(this.$e))}zc(){-1!==this.Wa&&(cancelAnimationFrame(this.Wa),this.Wa=-1)}Ne(){this.Wa=-1;for(const a of this.Va)a();this.Gc()}ea(a){this.ya.ea(a)}ia(a){this.ya.ia(a)}Fc(){this.ya.Fc()}Lb(a){this.ya.Lb(a)}se(){return!!ja["audio/webm; codecs=opus"]}async Te(a){a=await this.nd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}xe(a){this.Rc=!0;this.Dd=a}qe(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||
"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}md(a){return!this.qe(a)}async La(a){return"cordova"===this.B&&(a.startsWith("file:")||this.Ub&&this.md(a))?(a.startsWith(this.ca)&&(a=a.substr(this.ca.length)),a=await this.Gb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Je(a){const c=a.filename;switch(a.as){case "text":return await this.oe(c);case "buffer":return await this.Gb(c);default:throw Error("unsupported type");}}hd(a){const c=window.cordova.file.applicationDirectory+
"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async oe(a){a=await this.hd(a);return await ka(a)}Ac(){if(D.length&&!(8<=E)){E++;var a=D.shift();this.De(a.filename,a.lf,a.df)}}Gb(a){return new Promise((c,d)=>{D.push({filename:a,lf:e=>{E--;this.Ac();c(e)},df:e=>{E--;this.Ac();d(e)}});this.Ac()})}async De(a,c,d){try{const e=await this.hd(a),f=await la(e);c(f)}catch(e){d(e)}}Se(){var a={type:"ready"};if("windows-webview2"===this.B)window.chrome.webview.postMessage(JSON.stringify(a));
else if("macos-wkwebview"===this.B)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async Ce(){const a=[];for(const [c,d]of Object.entries(this.sa))a.push(this.Be(c,d));await Promise.all(a)}async Be(a,c){if("object"===typeof c)this.sa[a]=new Blob([c.str],{type:c.type}),this.Yb[a]=c.str;else{let d=await this.Fe(c);d||(d=this.Ee(c));this.sa[a]=d}}async Fe(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Ee(a){a=this.Qe(a);return this.Ae(a.data,a.gf)}Qe(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{gf:a,data:d}}Ae(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=
3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const H=self.gb;function ya(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const za=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Aa={dispatchUserScriptEvent:!0},Ba={dispatchRuntimeEvent:!0};
function Ca(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Da(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await Da(b)}finally{URL.revokeObjectURL(b)}}
function Ea(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Fa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await Ea(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Ga(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ha=new Set(["input","textarea","datalist","select"]),Ia=new Set(["canvas","body","html"]);function K(b){Ia.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ja(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Fa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ka=!1;document.addEventListener("pause",()=>Ka=!0);document.addEventListener("resume",()=>Ka=!1);function wa(b){b.Cd=!0;b.Vc=b.o.qa();b.sb=b.o.ja()}async function La(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ma(b){return await self.C3_GetSvgImageSize(b.blob)}
function Na(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Oa(b){self.setTimeout(()=>{b.Bd=!0},1E3);"cordova"===b.o.B?(document.addEventListener("pause",()=>Pa(b,!0)),document.addEventListener("resume",()=>Pa(b,!1))):document.addEventListener("visibilitychange",()=>Pa(b,document.hidden));return{isSuspended:!(!document.hidden&&!Ka)}}
function Qa(b){b.wd||(b.wd=!0,window.addEventListener("deviceorientation",a=>{b.$||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Ra(b){b.vd||(b.vd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Sa(b){await Ca(b.url)}
function Ta(b,a){b.Ed=a.message;-1===b.Mc&&(b.Mc=setTimeout(()=>{b.Mc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Ed)},250))}function L(b){if(!b.$){var a=H.eb();a&&"any"!==b.$c&&Ua(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ja()})}}function Va(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:H.eb(),innerWidth:b.qa(),innerHeight:b.ja()})}
function Pa(b,a){a?b.o.zc():b.o.Gc();k(b,"visibilitychange",{hidden:a})}function Wa(b,a,c){"Backspace"===c.key&&K(c);if(!b.$){var d=za.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function Xa(b,a,c,d){b.$||ya(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Ya(b){window!==window.top&&window.focus();Za(b.target)&&document.activeElement&&!Za(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.$){if(b.Ab&&"pointermove"!==a){var d=b.Ab;d.pb||(ba(d),d.Wb=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.xb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:(c.movementX||0)+b.fc,movementY:(c.movementY||0)+b.hc,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||
0,twist:c.twist||0,timeStamp:c.timeStamp},I);b.fc=0;b.hc=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Xa(b,d,c,Aa),b.xb=c.buttons)}}
function $a(b,a,c){if(!b.$&&!ya(c)){var d=b.xb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.xb=c.buttons;Xa(b,c.type,c,Aa)}}
function N(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function bb(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function cb(b,a,c,d){const e=b.qa(),f=b.ja();b.Ya=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.eb()}):10>d&&db(b,e,f,d+1)}
function db(b,a,c,d){-1!==b.Ya&&clearTimeout(b.Ya);b.Ya=setTimeout(()=>cb(b,a,c,d),48)}
function Ua(b){b=b.$c;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Za(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.Fb(class extends self.Hb{constructor(b){super(b,"runtime");this.Jd=!0;this.Cd=!1;this.Ya=-1;this.$c="any";this.vd=this.wd=!1;this.Ga=null;this.$=!1;this.Ed="";this.Mc=-1;this.Pa=this.Ab=null;this.hc=this.fc=0;this.Bd=!1;this.Vc=b.qa();this.sb=b.ja();this.da=this.Db=0;b.D("canvas","update-size",d=>{var e=this.o;e.Rc||(e=e.H,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",
d.displayScale),this.Jd&&(e.style.display="",this.Jd=!1))});b.D("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.D("runtime","raster-svg-image",d=>La(d));b.D("runtime","get-svg-image-size",d=>Ma(d));b.D("runtime","set-target-orientation",d=>{this.$c=d.targetOrientation});b.D("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.D("runtime",
"post-to-debugger",d=>Na(d));b.D("runtime","go-to-script",d=>Na(d));b.D("runtime","before-start-ticking",()=>Oa(this));b.D("runtime","debug-highlight",d=>{if(d.show){this.Ga||(this.Ga=document.createElement("div"),this.Ga.id="inspectOutline",document.body.appendChild(this.Ga));var e=this.Ga;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ga&&(this.Ga.style.display="none")});b.D("runtime",
"enable-device-orientation",()=>Qa(this));b.D("runtime","enable-device-motion",()=>Ra(this));b.D("runtime","add-stylesheet",d=>Sa(d));b.D("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.D("runtime","alert",d=>{alert(d.message)});b.D("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.D("runtime","set-exporting-to-video",d=>{this.$=!0;const e=
document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.o.H.style.display="";this.o.xe(d.duration)});b.D("runtime","export-to-video-progress",d=>Ta(this,d));b.D("runtime","exported-to-video",d=>{window.bf({type:"exported-video",blob:d.blob,time:d.time})});b.D("runtime","exported-to-image-sequence",d=>{window.bf({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input",
"textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ga(e)||d.preventDefault()});const c=b.H;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",K);window.addEventListener("touchstart",K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",
K);this.xb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ja,{passive:!1});window.addEventListener("wheel",Ja,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.Cd){var d=this.qa();var e=this.ja();if(this.o.uc()){if(this.Bd){if(this.Vc===d&&e<this.sb){this.Db=this.sb-e;bb(this,this.sb,this.Db);d=void 0;break a}0<this.Db&&(this.Db=0,bb(this,e,this.Db))}this.Vc=d;this.sb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,
devicePixelRatio:window.devicePixelRatio,isFullscreen:H.eb()});this.o.vc()&&(-1!==this.Ya&&clearTimeout(this.Ya),cb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",()=>L(this));window.addEventListener("mozfullscreenchange",()=>L(this));window.addEventListener("fullscreenerror",d=>Va(this,d));window.addEventListener("webkitfullscreenerror",d=>Va(this,d));window.addEventListener("mozfullscreenerror",d=>Va(this,
d));if(b.vc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ga(f)}else d=!1}d||(document.scrollingElement.scrollTop=
0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(H.ud(!0),L(this)):"exited-fullscreen"===d?(H.ud(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Ra=new Set;this.$b=new WeakSet;this.wa=!1}ed(){window.addEventListener("focus",()=>{k(this,"window-focus",null,Ba)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},Ba);this.xb=0});window.addEventListener("focusin",a=>{a=a.target;
(Ha.has(a.tagName.toLowerCase())||Ga(a))&&k(this,"keyboard-blur",null,Ba)});window.addEventListener("keydown",a=>Wa(this,"keydown",a));window.addEventListener("keyup",a=>Wa(this,"keyup",a));window.addEventListener("dblclick",a=>Xa(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.$||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==
typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Ya(a);M(this,"pointerdown",a)}),this.o.oa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.Ab=new self.we(()=>{M(this,"pointermove",this.Pa);this.Pa=null}),this.Ab.zd=!0,window.addEventListener("pointerrawupdate",a=>{this.Pa&&(this.fc+=this.Pa.movementX||0,this.hc+=this.Pa.movementY||0);this.Pa=a;a=this.Ab;if(-1===a.Za){var c=Date.now(),d=c-a.Wb,e=a.Ve;d>=e&&a.zd?(a.Wb=c,a.pb=!0,a.Ic(),a.pb=!1):a.Za=self.setTimeout(a.Xd,
Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Ya(a);$a(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>$a(this,"pointermove",a)),window.addEventListener("mouseup",a=>$a(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Ya(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",
a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=()=>this.Fc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.o.re()&&!this.o.uc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",
()=>{bb(this,this.ja(),navigator.virtualKeyboard.boundingRect.height)}))}qa(){return this.o.qa()}ja(){return this.o.ja()}Fc(){var b=[...this.Ra];this.Ra.clear();if(!this.wa)for(const a of b)(b=a.play())&&b.catch(()=>{this.$b.has(a)||this.Ra.add(a)})}ea(b){if("function"!==typeof b.play)throw Error("missing play function");this.$b.delete(b);let a;try{a=b.play()}catch(c){this.Ra.add(b);return}a&&a.catch(()=>{this.$b.has(b)||this.Ra.add(b)})}ia(b){this.Ra.delete(b);this.$b.add(b)}Lb(b){this.wa=!!b}});
"use strict";async function ua(b){if(b.Ue)throw Error("already initialised");b.Ue=!0;var a=b.za.Bc(("playable-ad"===b.za.B?b.za.Xa:"")+"dispatchworker.js");b.Lc=await b.za.pc(a,b.jb,{name:"DispatchWorker"});a=new MessageChannel;b.Qc=a.port1;b.Lc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Yc=await xa(b)}function va(b){return[b.Qc,b.Yc]}
async function xa(b){const a=b.Kd.length;var c=b.za.Bc(("playable-ad"===b.za.B?b.za.Xa:"")+"jobworker.js");c=await b.za.pc(c,b.jb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Lc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Kd.push(c);return e.port1}
self.ue=class{constructor(b){this.za=b;this.jb=b.ca;this.jb="preview"===b.B?this.jb+"workers/":this.jb+b.Xa;this.Xe=Math.min(navigator.hardwareConcurrency||2,16);this.Lc=null;this.Kd=[];this.Yc=this.Qc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.gb({mf:!0,nf:"workermain.js",$a:["scripts/c3runtime.js"],nc:[],bd:"",jf:"scripts/",dd:[],Yd:"html5"}));"use strict";
self.gb.Fb(class extends self.Hb{constructor(b){super(b,"mouse");t(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.o.H.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function eb(b,a){b.Tc=a.isInWorker;a=document.createElement("video");b.kc=!!a.requestVideoFrameCallback&&!b.o.uc();const c=!!self.createImageBitmap;b.Bb=b.Tc||c;return{postImageBitmaps:b.Bb,supportedFormats:{"video/webm":!!a.canPlayType("video/webm"),"video/ogg":!!a.canPlayType("video/ogg"),"video/mp4":!!a.canPlayType("video/mp4")}}}
async function fb(b,a){if(!b.Kc.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>fb(b,a));try{const c=a.c3_sequenceNumber++,d=await createImageBitmap(a);c>a.c3_lastFrameSequence&&(a.c3_imageBitmap=d,a.c3_lastFrameSequence=c)}catch(c){}}}function O(b,a,c,d){b.Kc.has(a)||v(b,"playback-event",c,{type:d})}
self.gb.Fb(class extends self.pe{constructor(b){super(b);this.Bb=this.kc=this.Tc=this.ib=!1;this.ac=this.af=0;this.Kc=new WeakSet;p(this,"init",a=>eb(this,a));w(this,"play",a=>{this.ea(a)});w(this,"pause",a=>{this.ia(a);a.pause()});w(this,"set-source",(a,c)=>{a.src=c.src;a.load()});w(this,"set-playback-time",(a,c)=>{try{a.currentTime=c.time}catch(d){console.error("[Video] Exception setting playback time: ",d)}});w(this,"set-playback-rate",(a,c)=>{try{a.playbackRate=c.rate}catch(d){console.error("[Video] Exception setting playback rate: ",
d)}});w(this,"set-looping",(a,c)=>{a.loop=c.isLooping});w(this,"set-muted",(a,c)=>{a.muted=c.isMuted});w(this,"set-volume",(a,c)=>{a.volume=c.volume});self.C3Video_GetElement=a=>this.X.get(a)}ea(b){this.o.ea(b);this.Bb&&this.kc&&-1===b.c3_rvfcId&&(b.c3_rvfcId=b.requestVideoFrameCallback(()=>fb(this,b)))}ia(b){this.o.ia(b);this.Bb&&this.kc&&-1!==b.c3_rvfcId&&(b.cancelVideoFrameCallback(b.c3_rvfcId),b.c3_rvfcId=-1)}jd(b,a){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=
!0;c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",()=>O(this,c,b,0));c.addEventListener("canplaythrough",()=>O(this,c,b,1));c.addEventListener("ended",()=>O(this,c,b,2));c.addEventListener("error",()=>O(this,c,b,3));c.addEventListener("loadstart",()=>O(this,c,b,4));c.addEventListener("playing",()=>O(this,c,b,5));c.addEventListener("pause",()=>O(this,c,b,6));c.addEventListener("stalled",()=>O(this,c,b,7));const d=a.autoplay;0===d?(c.autoplay=
!1,c.preload="none"):1===d?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;a.src&&(c.src=a.src);2===d&&this.ea(c);this.ac++;u(this);return c}od(){}ld(b){this.ia(b);b&&!b.paused&&!b.ended&&0<b.currentTime&&b.pause();b.src="";this.ac=Math.max(this.ac-1,0);0===this.ac&&aa(this);this.Kc.add(b)}Da(){const b={},a={sequenceNumber:this.af++,videoData:b},c=[],d=[];for(const [e,f]of this.X.entries()){const g={currentTime:f.currentTime,playbackRate:f.playbackRate,duration:f.duration,videoWidth:f.videoWidth,videoHeight:f.videoHeight};
if(this.Bb)if(this.kc){const h=f.c3_imageBitmap;f.c3_imageBitmap=null;(g.imageBitmap=h)&&c.push(h)}else d.push(createImageBitmap(f).then(h=>{g.imageBitmap=h;c.push(h)}).catch(()=>{g.imageBitmap=null}));b[e.toString()]=g}Promise.all(d).then(()=>{this.Tc?k(this,"state",a,!1,c):l(this,"state",a)})}});"use strict";const hb=180/Math.PI;
async function ib(b,a){if(a.isiOSCordova||a.isSafari)b.dc=!0;b.ad=a.timeScaleMode;b.Pd=["equalpower","HRTF","soundfield"][a.panningModel];b.Ad=["linear","inverse","exponential"][a.distanceModel];b.Qd=a.refDistance;b.Od=a.maxDistance;b.Sd=a.rolloffFactor;if(b.o.Rc)b.dc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.o.Dd)});else{var c={latencyHint:a.latencyHint};b.Vd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");jb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&jb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Na=b.g.createGain();b.Na.connect(b.g.destination);c=a.listenerPos;b.ba[0]=c[0];b.ba[1]=c[1];b.ba[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function kb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,q=a.pos,n=a.panning,B=a.stereoPan;let y=a.off;0<y&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+b.g.currentTime);b.Ld=g;lb(b,g);try{b.aa=await mb(b,c,d,e,g,f);if(n){Q(b.aa,!0);var r=b.aa,C=n.innerAngle,na=n.outerAngle,oa=n.outerGain;if(r.qb){nb(r,n.x,n.y,n.angle);var F=self.ab.ye;r.ta[0]!==F(C)&&(r.ta[0]=
F(C),r.F.coneInnerAngle=F(C));r.ta[1]!==F(na)&&(r.ta[1]=F(na),r.F.coneOuterAngle=F(na));r.ta[2]!==oa&&(r.ta[2]=oa,r.F.coneOuterGain=oa)}n.hasOwnProperty("uid")&&(b.aa.ra=n.uid)}else"number"===typeof B&&0!==B?(R(b.aa,!0),ob(b.aa,B)):(Q(b.aa,!1),R(b.aa,!1));b.aa.Play(h,m,q,y)}catch(zb){console.error("[Construct] Audio: error starting playback: ",zb);return}finally{c=b.zb.get(g);if(!c)throw Error("expected pending tag");c.cd--;0===c.cd&&(c.resolve(),b.zb.delete(g))}u(b)}
async function pb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await qb(b,c);for(const n of S(b,c)){c=n;var f=d,g=e,h=a;if(!c.Oa){var m=c.G.gain;m.cancelScheduledValues(0);var q=c.u.g.currentTime;g=q+g;m.setValueAtTime(m.value,q);m.linearRampToValueAtTime(f,g);c.Ja=f;c.nb=g;c.Ud=h}}T(b)}async function rb(b,a){const c=a.tag;a=a.rate;await qb(b,c);for(const d of S(b,c))b=d,b.na!==a&&(b.na=a,b.Ea())}
async function sb(b,a){const c=a.tag;a=a.pos;await qb(b,c);for(const d of S(b,c))d.wc(a)}async function tb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await mb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function ub(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.la.indexOf(a),-1!==a&&b.la.splice(a,1)}
async function vb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.de(b,...e);else if("delay"===c)e=new self.be(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.ae(b,c.ka,...e);var f=a.bufferType;c.xd=a.bufferOriginalUrl;c.yd=f}else if("flanger"===c)e=new self.ee(b,...e);else if("phaser"===c)e=new self.ge(b,...e);else if("gain"===c)e=
new self.fe(b,...e);else if("stereopan"===c)e=new self.ie(b,...e);else if("tremolo"===c)e=new self.je(b,...e);else if("ringmod"===c)e=new self.he(b,...e);else if("distortion"===c)e=new self.ce(b,...e);else if("compressor"===c)e=new self.$d(b,...e);else if("analyser"===c)e=new self.Zd(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.ma.get(d);e||(e=[],b.ma.set(d,e));a.Id=e.length;a.ga=d;e.push(a);wb(b,d);xb(b)}
async function yb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(const e of b.J)e.Ba()&&1===c||!e.Ba()&&2===c?d.push(e):e.j();b.J=d}for(const e of b.ma.values())for(const f of e)f.j();b.ma.clear();b.lc=a.timeScale;b.Nc=a.gameTime;d=a.listenerPos;b.ba[0]=d[0];b.ba[1]=d[1];b.ba[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);b.wa=a.isSilent;b.o.Lb(b.wa);b.Zb=a.masterVolume;b.Na.gain.value=b.Zb;d=[];for(const e of Object.values(a.effects))d.push(Promise.all(e.map(f=>vb(b,f))));await Promise.all(d);
await Promise.all(a.playing.map(e=>Ab(b,e,c)));T(b)}async function Bb(b,a){try{const c=b.g.suspend(a.time);b.Hd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.o.Jb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Cb(d)),b.Hd=!0);await c}catch(c){Cb(c)}}
function jb(b){b.Sb||(b.Pc=!1,window.addEventListener("pointerup",b.Aa,!0),window.addEventListener("touchend",b.Aa,!0),window.addEventListener("click",b.Aa,!0),window.addEventListener("keydown",b.Aa,!0),b.Sb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.la)if(g.cb()===c)return await Db(g),g;if(f)return null;if(e&&(b.dc||b.Gd)){f=0;for(let h=0,m=b.la.length;h<m;++h)g=b.la[h],b.la[f]=g,g.Ba()?g.j():++f;b.la.length=f}f="audio/webm; codecs=opus"===d&&!b.Vd;e&&f&&(b.Gd=!0);c=!e||b.dc||f?new self.me(b,a,c,d,e,f):new self.ke(b,a,c,d,e);b.la.push(c);await Db(c);b.Nd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Nd.add(a));return c}
function Eb(b,a){return(a=b.ma.get(a.toLowerCase()))?a[0].N():b.pa()}function wb(b,a){let c=b.pa();var d=b.ma.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.S(b.pa()):e.S(d[f+1].N())}}for(const f of S(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Ha&&b.Wc===a&&(b.Ha.disconnect(),b.Ha.connect(c))}
function*S(b,a){if(a)for(const c of b.J)b=c.ga,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.aa&&!b.aa.U()&&(yield b.aa)}function Fb(b,a,c){return c?b.o.Te(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Gb(b,a){let c=0;for(let d=0,e=b.J.length;d<e;++d){const f=b.J[d];b.J[c]=f;f.O===a?f.j():++c}b.J.length=c}
async function mb(b,a,c,d,e,f){for(const g of b.J)if(g.cb()===c&&(g.oc()||f))return g.ga=e,g;a=await P(b,a,c,d,f);e="html5"===a.Hc?new self.le(a.u,a,e):new self.ne(a.u,a,e);b.J.push(e);return e}function lb(b,a){let c=b.zb.get(a);if(!c){let d=null;c={cd:0,promise:new Promise(e=>d=e),resolve:d};b.zb.set(a,c)}c.cd++}function qb(b,a){a||(a=b.Ld);return(b=b.zb.get(a))?b.promise:Promise.resolve()}function T(b){if(0<b.Ma.size)u(b);else for(const a of b.J)if(!a.I&&!a.U()){u(b);break}}
function Ib(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function xb(b){b.Sc||(b.Sc=!0,Promise.resolve().then(()=>Jb(b)))}function Jb(b){const a={};for(const [c,d]of b.ma)a[c]=d.map(e=>e.bb());k(b,"fxstate",{fxstate:a});b.Sc=!1}
async function Ab(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,q=a.volume,n=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await mb(b,d,e,f,h,g)}catch(B){console.error("[Construct] Audio: error loading audio state: ",B);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],f=d.orient,b.Sa[0]=f[0],b.Sa[1]=f[1],b.Sa[2]=f[2],e.setPosition(...b.Ta),e.setOrientation(...b.Sa),b.ta[0]=d.cia,b.ta[1]=d.coa,b.ta[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ra=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),ob(b,d));c.Play(m,q,n,0);a.isPlaying||c.fb();c.Dc(a)}}}function Cb(b){console.error("[Audio] Offline rendering error: ",b)}
self.ab=class extends self.Hb{constructor(b){super(b,"audio");this.Na=this.g=null;this.Sb=this.Pc=!1;this.Aa=()=>{if(!this.Pc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Sb&&(this.Pc=!0,window.removeEventListener("pointerup",this.Aa,!0),window.removeEventListener("touchend",this.Aa,!0),window.removeEventListener("click",this.Aa,!0),window.removeEventListener("keydown",
this.Aa,!0),this.Sb=!1)}};this.la=[];this.J=[];this.aa=null;this.Ld="";this.Nd=new Set;this.Md=-1;this.zb=new Map;this.Zb=1;this.wa=!1;this.ad=0;this.lc=1;this.Nc=0;this.Pd="HRTF";this.Ad="inverse";this.Qd=600;this.Od=1E4;this.Sd=1;this.ba=[0,0,0];this.Gd=this.dc=!1;this.Vd=this.o.se();this.ma=new Map;this.Ma=new Set;this.Hd=this.Sc=!1;this.Wc="";this.Ha=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ha&&this.Ha.disconnect();this.Wc=c.toLowerCase();this.Ha=this.g.createMediaStreamSource(a);this.Ha.connect(Eb(this,
this.Wc))};this.Qb=null;self.C3Audio_GetOutputStream=()=>{this.Qb||(this.Qb=this.g.createMediaStreamDestination(),this.Na.connect(this.Qb));return this.Qb.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>ib(this,a)],["play",a=>kb(this,a)],["stop",a=>{a=a.tag;for(const c of S(this,a))c.Ca()}],["stop-all",()=>{for(const a of this.J)a.Ca()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of S(this,c))a?d.fb():d.Kb();T(this)}],["set-volume",a=>{const c=a.tag;a=a.vol;for(const d of S(this,
c))U(d,a)}],["fade-volume",a=>pb(this,a)],["set-master-volume",a=>{this.Zb=a.vol;this.Na.gain.value=this.Zb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of S(this,c))Kb(d,a)}],["set-silent",a=>{this.wa=a.isSilent;this.o.Lb(this.wa);for(const c of this.J)c.Ob()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of S(this,c))d.xc(a)}],["set-playback-rate",a=>rb(this,a)],["set-stereo-pan",a=>{const c=a.tag;a=a.p;for(const d of S(this,c))R(d,!0),ob(d,a)}],["seek",a=>sb(this,a)],
["preload",a=>tb(this,a)],["unload",a=>ub(this,a)],["unload-all",()=>{for(const a of this.la)a.j();this.la.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.J)c.yc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>vb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.ma.get(a.tag);!a||0>c||c>=a.length||(a[c].Z(d,e,f,g),xb(this))}],["remove-effects",a=>{a=a.tag.toLowerCase();const c=this.ma.get(a);
if(c&&c.length){for(const d of c)d.j();this.ma.delete(a);wb(this,a)}}],["tick",a=>{this.lc=a.timeScale;this.Nc=a.gameTime;this.Md=a.tickCount;if(0!==this.ad)for(var c of this.J)c.Ea();!(c=a.listenerPos)||this.ba[0]===c[0]&&this.ba[1]===c[1]&&this.ba[2]===c[2]||(this.ba[0]=c[0],this.ba[1]=c[1],this.ba[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));for(const d of a.instPans){a=d.uid;for(const e of this.J)e.ra===a&&nb(e,d.x,d.y,d.angle)}}],["load-state",a=>yb(this,a)],["offline-render-audio",a=>
Bb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}pa(){return this.Na}Ib(){return this.wa}ea(b){this.o.ea(b)}ia(b){this.o.ia(b)}Da(){for(var b of this.Ma)b.Da();b=this.g.currentTime;for(var a of this.J)a.Da(b);a=this.J.filter(c=>!c.I&&!c.U()).map(c=>c.bb());k(this,"state",{tickCount:this.Md,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ma].map(c=>({tag:c.ga,index:c.Id,peak:c.Ua,rms:c.Rd,binCount:c.l.frequencyBinCount,freqBins:c.Fd}))});0===
a.length&&0===this.Ma.size&&aa(this)}static ye(b){return b*hb}static kd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static ve(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.gb.Fb(self.ab);"use strict";function Db(b){b.Xb||(b.Xb=b.Cc());return b.Xb}self.fd=class{constructor(b,a,c,d,e){this.u=b;this.Ze=a;this.Ia=c;this.R=d;this.We=e;this.Hc="";this.Xb=null}j(){this.Xb=this.u=null}Cc(){}V(){return this.u.V()}rc(){return this.Ze}cb(){return this.Ia}qc(){return this.R}Ba(){return this.We}ha(){}};
"use strict";
self.ke=class extends self.fd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Hc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.tb=this.ub=null;this.M.addEventListener("canplaythrough",()=>!0);this.yb=this.V().createGain();this.wb=null;this.M.addEventListener("canplay",()=>{this.ub&&(this.ub(),this.tb=this.ub=null);!this.wb&&this.M&&(this.wb=this.V().createMediaElementSource(this.M),this.wb.connect(this.yb))});this.onended=null;this.M.addEventListener("ended",()=>
{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ia}' error: `,f);this.tb&&(this.tb(f),this.tb=this.ub=null)})}j(){Gb(this.u,this);this.yb.disconnect();this.yb=null;this.wb.disconnect();this.wb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}Cc(){return new Promise((b,a)=>{this.ub=b;this.tb=a;this.M.src=this.Ia})}T(){return this.M}ha(){return this.M.duration}};"use strict";
async function Lb(b){if(b.Fa)return b.Fa;var a=b.u.o;if("cordova"===a.B&&a.md(b.Ia)&&a.Ub)b.Fa=await a.Gb(b.Ia);else{a=await fetch(b.Ia);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Fa=await a.arrayBuffer()}}async function Mb(b){if(b.ka)return b.ka;b.ka=await Fb(b.u,b.Fa,b.Ye);b.Fa=null}
self.me=class extends self.fd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Hc="webaudio";this.ka=this.Fa=null;this.Ye=!!f}j(){Gb(this.u,this);this.ka=this.Fa=null;super.j()}async Cc(){try{await Lb(this),await Mb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ia}': `,b)}}ha(){return this.ka?this.ka.duration:0}};"use strict";let Nb=0;
function Q(b,a){a=!!a;b.qb!==a&&(b.qb=a,b.qb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Pd,b.F.distanceModel=b.u.Ad,b.F.refDistance=b.u.Qd,b.F.maxDistance=b.u.Od,b.F.rolloffFactor=b.u.Sd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.pa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.pa())))}
function R(b,a){a=!!a;b.Vb!==a&&(b.Vb=a,b.Vb?(Q(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.pa())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.pa())))}function ob(b,a){b.Vb&&b.Zc!==a&&(b.fa.pan.value=a,b.Zc=a)}function U(b,a){b.Ja=a;b.G.gain.cancelScheduledValues(0);b.nb=-1;b.G.gain.value=b.sc()}function Kb(b,a){a=!!a;b.Oa!==a&&(b.Oa=a,b.Ob())}
function nb(b,a,c,d){if(b.qb){var e=b.Ta,f=b.Sa,g=Math.cos(d);d=Math.sin(d);if(e[0]!==a||e[1]!==c||0!==e[2])e[0]=a,e[1]=c,e[2]=0,b.F.setPosition(...e);if(f[0]!==g||f[1]!==d||0!==f[2])f[0]=g,f[1]=d,f[2]=0,b.F.setOrientation(...f)}}function V(b){return b.Uc?b.u.Nc:performance.now()/1E3}
self.gd=class{constructor(b,a,c){this.u=b;this.O=a;this.ga=c;this.Pb=Nb++;this.G=this.V().createGain();this.G.connect(this.pa());this.F=null;this.qb=!1;this.Ta=[0,0,0];this.Sa=[0,0,0];this.ta=[0,0,0];this.fa=null;this.Vb=!1;this.Zc=0;this.I=!0;this.Y=this.ua=this.K=!1;this.Ja=1;this.Oa=!1;this.na=1;b=this.u.ad;this.Uc=1===b&&!this.Ba()||2===b;this.nb=this.ra=-1;this.Ud=!1}j(){this.O=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}pa(){return Eb(this.u,this.ga)}rc(){return this.O.rc()}cb(){return this.O.cb()}qc(){return this.O.qc()}Ba(){return this.O.Ba()}U(){}oc(){}IsPlaying(){return!this.I&&!this.K&&!this.U()}Ka(){}ha(){return this.O.ha()}Play(){}Ca(){}fb(){}Kb(){}Da(b){-1!==this.nb&&b>=this.nb&&(this.nb=-1,this.Ud&&this.Ca(),Ib(this.u,"fade-ended",this.ga,this.Pb))}sc(){const b=this.Ja;return isFinite(b)?b:0}Ib(){return this.u.Ib()}Ob(){}xc(){}Ea(){}wc(){}yc(){}tc(){}bb(){var b=this.Pb,
a=this.ga,c=this.ha(),d=this.Ja,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ta,orient:this.Sa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ra}}else f=null;return{aiid:b,tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ka(),playbackRate:this.na,uid:this.ra,bufferOriginalUrl:this.rc(),bufferUrl:"",bufferType:this.qc(),isMusic:this.Ba(),isLooping:this.Y,isMuted:this.Oa,resumePosition:this.tc(),pan:f,stereoPan:this.fa?this.Zc:null}}Dc(b){var a=b.playbackRate;
this.na!==a&&(this.na=a,this.Ea());Kb(this,b.isMuted)}};"use strict";
self.le=class extends self.gd{constructor(b,a,c){super(b,a,c);this.O.yb.connect(this.G);this.O.onended=()=>this.Ec()}j(){this.Ca();this.O.yb.disconnect();super.j()}T(){return this.O.T()}Ec(){this.I=!0;this.ra=-1;Ib(this.u,"ended",this.ga,this.Pb)}U(){return this.T().ended}oc(){return this.I?!0:this.U()}Ka(){let b=this.T().currentTime;this.Y||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.T();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.O.cb()}' to position '${c}': `,e)}this.u.ea(d);this.K=this.I=!1;this.Y=b;this.na=1}Ca(){const b=this.T();b.paused||b.pause();this.u.ia(b);this.I=!0;this.K=!1;this.ra=-1}fb(){if(!(this.K||this.I||this.U())){var b=this.T();b.paused||b.pause();this.u.ia(b);this.K=!0}}Kb(){!this.K||this.I||this.U()||(this.u.ea(this.T()),this.K=!1)}Ob(){this.T().muted=this.Oa||this.Ib()}xc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.T().loop=b)}Ea(){let b=this.na;this.Uc&&(b*=this.u.lc);try{this.T().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}wc(b){if(!this.I&&!this.U())try{this.T().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}tc(){return this.Ka()}yc(b){b?this.IsPlaying()?(this.T().pause(),this.ua=!0):this.ua=!1:this.ua&&(this.u.ea(this.T()),this.ua=!1)}};"use strict";function W(b){b.s&&b.s.disconnect();b.s=null;b.hb=null}
self.ne=class extends self.gd{constructor(b,a,c){super(b,a,c);this.s=null;this.bc=d=>this.Ec(d);this.Oc=!0;this.hb=null;this.P=this.cc=this.ec=0;this.Xc=1}j(){this.Ca();W(this);this.bc=null;super.j()}Ec(b){this.K||this.ua||b.target!==this.hb||(this.I=this.Oc=!0,this.ra=-1,W(this),Ib(this.u,"ended",this.ga,this.Pb))}U(){return!this.I&&this.s&&this.s.loop||this.K?!1:this.Oc}oc(){return!this.s||this.I?!0:this.U()}Ka(){let b;b=this.K?this.P:this.cc+(V(this)-this.ec)*this.na;this.Y||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Xc=1;U(this,a);W(this);this.s=this.V().createBufferSource();this.s.buffer=this.O.ka;this.s.connect(this.G);this.hb=this.s;this.s.onended=this.bc;this.s.loop=b;this.s.start(d,c);this.K=this.I=this.Oc=!1;this.Y=b;this.na=1;this.ec=V(this);this.cc=c}Ca(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.K=!1;this.ra=-1}fb(){this.K||this.I||this.U()||(this.P=this.Ka(),this.Y&&(this.P%=this.ha()),this.K=!0,this.s.stop(0))}Kb(){!this.K||this.I||this.U()||(W(this),this.s=
this.V().createBufferSource(),this.s.buffer=this.O.ka,this.s.connect(this.G),this.hb=this.s,this.s.onended=this.bc,this.s.loop=this.Y,U(this,this.Ja),this.Ea(),this.s.start(0,this.P),this.ec=V(this),this.cc=this.P,this.K=!1)}sc(){return super.sc()*this.Xc}Ob(){this.Xc=this.Oa||this.Ib()?0:1;U(this,this.Ja)}xc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ea(){let b=this.na;this.Uc&&(b*=this.u.lc);this.s&&(this.s.playbackRate.value=b)}wc(b){this.I||this.U()||(this.K?this.P=b:(this.fb(),this.P=
b,this.Kb()))}tc(){return this.P}yc(b){b?this.IsPlaying()?(this.ua=!0,this.P=this.Ka(),this.Y&&(this.P%=this.ha()),this.s.stop(0)):this.ua=!1:this.ua&&(W(this),this.s=this.V().createBufferSource(),this.s.buffer=this.O.ka,this.s.connect(this.G),this.hb=this.s,this.s.onended=this.bc,this.s.loop=this.Y,U(this,this.Ja),this.Ea(),this.s.start(0,this.P),this.ec=V(this),this.cc=this.P,this.ua=!1)}Dc(b){super.Dc(b);this.P=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Id=-1;this.R=this.ga="";this.m=null}j(){this.g=null}N(){}S(){}bb(){return{type:this.R,tag:this.ga,params:this.m}}}
self.de=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="filter";this.m=[a,c,d,e,f,g];this.v=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.C=this.g.createBiquadFilter();this.C.type=a;this.C.frequency.value=c;this.C.detune.value=d;this.C.Q.value=e;this.C.gain.vlaue=f;this.v.connect(this.C);this.v.connect(this.h);this.C.connect(this.i)}j(){this.v.disconnect();this.C.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.C.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.C.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.C.gain,a,c,d)}}};
self.be=class extends Z{constructor(b,a,c,d){super(b);this.R="delay";this.m=[a,c,d];this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.vb=X(this);this.W=this.g.createDelay(a);this.W.delayTime.value=a;this.mb=X(this);this.mb.gain.value=c;this.v.connect(this.vb);this.v.connect(this.h);this.vb.connect(this.i);this.vb.connect(this.W);this.W.connect(this.mb);this.mb.connect(this.vb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.vb.disconnect();
this.W.disconnect();this.mb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.ab.kd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.mb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.W.delayTime,a,c,d)}}};
self.ae=class extends Z{constructor(b,a,c,d){super(b);this.R="convolution";this.m=[c,d];this.yd=this.xd="";this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.lb=this.g.createConvolver();this.lb.normalize=c;this.lb.buffer=a;this.v.connect(this.lb);this.v.connect(this.h);this.lb.connect(this.i)}j(){this.v.disconnect();this.lb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}bb(){const b=super.bb();b.bufferOriginalUrl=this.xd;b.bufferUrl="";b.bufferType=this.yd;return b}};
self.ee=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="flanger";this.m=[a,c,d,e,f];this.v=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.ob=X(this);this.ob.gain.value=e;this.W=this.g.createDelay(a+c);this.W.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.v.connect(this.W);this.v.connect(this.h);this.W.connect(this.i);this.W.connect(this.ob);this.ob.connect(this.W);this.A.connect(this.L);
this.L.connect(this.W.delayTime);this.A.start(0)}j(){this.A.stop(0);this.v.disconnect();this.W.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.ob.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.A.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.ob.gain,a/100,c,d)}}};
self.ge=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="phaser";this.m=[a,c,d,e,f,g];this.v=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.C=this.g.createBiquadFilter();this.C.type="allpass";this.C.frequency.value=a;this.C.detune.value=c;this.C.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.v.connect(this.C);this.v.connect(this.h);this.C.connect(this.i);this.A.connect(this.L);this.L.connect(this.C.frequency);
this.A.start(0)}j(){this.A.stop(0);this.v.disconnect();this.C.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.C.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.C.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.A.frequency,a,c,d)}}};self.fe=class extends Z{constructor(b,a){super(b);this.R="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.ab.kd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.ie=class extends Z{constructor(b,a){super(b);this.R="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.je=class extends Z{constructor(b,a,c){super(b);this.R="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.A.connect(this.L);this.L.connect(this.l.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.L.disconnect();this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.he=class extends Z{constructor(b,a,c){super(b);this.R="ringmod";this.m=[a,c];this.v=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Cb=X(this);this.Cb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.Cb.gain);this.A.start(0);this.v.connect(this.Cb);this.v.connect(this.h);this.Cb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.Cb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.ce=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="distortion";this.m=[a,c,d,e,f];this.v=X(this);this.jc=X(this);this.ic=X(this);b=d;.01>b&&(b=.01);this.jc.gain.value=b;this.ic.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.mc=this.g.createWaveShaper();this.Jc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Jc[32768+e]=f,this.Jc[32768-
e-1]=-f;this.mc.curve=this.Jc;this.v.connect(this.jc);this.v.connect(this.h);this.jc.connect(this.mc);this.mc.connect(this.ic);this.ic.connect(this.i)}j(){this.v.disconnect();this.jc.disconnect();this.mc.disconnect();this.ic.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.$d=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.Zd=class extends Z{constructor(b,a,c){super(b);this.R="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Fd=new Float32Array(this.l.frequencyBinCount);this.Td=new Uint8Array(a);this.Rd=this.Ua=0;b=this.u;b.Ma.add(this);T(b)}j(){this.u.Ma.delete(this);this.l.disconnect();super.j()}Da(){this.l.getFloatFrequencyData(this.Fd);this.l.getByteTimeDomainData(this.Td);const b=this.l.fftSize;let a=this.Ua=0;for(var c=0;c<b;++c){let d=(this.Td[c]-
128)/128;0>d&&(d=-d);this.Ua<d&&(this.Ua=d);a+=d*d}c=self.ab.ve;this.Ua=c(this.Ua);this.Rd=c(Math.sqrt(a/b))}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
