function l(b,a,c,d,e){b.g.xa(b.S,a,c,d,e)}function m(b,a,c,d){b.g.u?l(b,a,c,d):b.g.Eb()._OnMessageFromDOM({type:"event",component:b.S,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.g.h(b.S,a,c)}function p(b,a){for(const [c,d]of a)n(b,c,d)}window.ua=class{constructor(b,a){this.g=b;this.S=a;this.fa=!1;this.kb=()=>this.Ra()}Na(){}Ra(){}};
window.vb=class{constructor(b){this.bb=b;this.Sb=5;this.M=-1;this.ga=-Infinity;this.Xb=()=>{this.M=-1;this.ga=Date.now();this.T=!0;this.bb();this.T=!1};this.cb=this.T=!1}};"use strict";function aa(b,a){const c=a.elementId,d=b.Pa(c,a);b.l.set(c,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{q(b,"elem-focused",c)});d.addEventListener("blur",()=>{q(b,"elem-blurred",c)});b.P&&document.body.appendChild(d)}
function r(b,a,c){n(b,a,d=>{const e=b.l.get(d.elementId);return c(e,d)})}function q(b,a,c,d){d||(d={});d.elementId=c;l(b,a,d)}
window.ob=class extends self.ua{constructor(b){super(b,"video");this.l=new Map;this.P=!0;p(this,[["create",a=>aa(this,a)],["destroy",a=>{a=a.elementId;const c=this.l.get(a);this.Qa(c);this.P&&c.parentElement.removeChild(c);this.l.delete(a)}],["set-visible",a=>{this.P&&(this.l.get(a.elementId).style.display=a.isVisible?"":"none")}],["update-position",a=>{if(this.P){var c=this.l.get(a.elementId);c.style.left=a.left+"px";c.style.top=a.top+"px";c.style.width=a.width+"px";c.style.height=a.height+"px";
a=a.fontSize;null!==a&&(c.style.fontSize=a+"em")}}],["update-state",a=>{this.l.get(a.elementId);this.Sa()}],["focus",a=>{const c=this.l.get(a.elementId);a.focus?c.focus():c.blur()}],["set-css-style",a=>{this.l.get(a.elementId).style[a.prop]=a.val}],["set-attribute",a=>{this.l.get(a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{this.l.get(a.elementId).removeAttribute(a.name)}]]);r(this,"get-element",a=>a)}Pa(){throw Error("required override");}Qa(){}Sa(){throw Error("required override");
}};"use strict";const t=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),u=/android/i.test(navigator.userAgent);let w=0;function x(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.bc?new Promise(c=>{const d="c3_resolve_"+w;++w;self[d]=c;a.textContent=b.fc+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let y=!1,z=!1;
function ca(){if(!y){try{new Worker("blob://",{get type(){z=!0}})}catch(b){}y=!0}return z}let A=new Audio;const da={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;
async function ea(b){b=await B(b);return(new TextDecoder("utf-8")).decode(b)}function B(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let fa=0;const H=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");H.push(b)};const ha=new Set(["cordova","playable-ad","instant-games"]);let ia=!1;
window.ba=class b{constructor(a){this.u=a.ic;this.V=null;this.s="";this.oa=a.ec;this.aa={};this.Ia=this.lb=null;this.ea=[];this.j=this.Z=null;this.gb=!1;this.U=null;this.K=-1;this.Vb=()=>this.Lb();this.J=[];this.i=a.mb;this.Ga="file"===location.protocol.substr(0,4);!this.u||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ca()||(this.u=!1);if("playable-ad"===this.i||"instant-games"===this.i)this.u=!1;if("cordova"===this.i&&this.u)if(u){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.u=!1)}else this.u=!1;this.ia=this.A=null;"html5"!==this.i||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime","cordova-fetch-local-file",c=>this.Hb(c));this.h("runtime","create-job-worker",()=>this.Ib());"cordova"===this.i?document.addEventListener("deviceready",()=>this.Wa(a)):this.Wa(a)}sb(){return t&&
"cordova"===this.i}wa(){const a=navigator.userAgent;return t&&ha.has(this.i)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}qb(){return u}va(){return u&&ha.has(this.i)}async Wa(a){"macos-wkwebview"===this.i&&this.Qb();if("playable-ad"===this.i){this.A=self.c3_base64files;this.ia={};await this.Ab();for(let d=0,e=a.N.length;d<e;++d){var c=a.N[d].toLowerCase();this.ia.hasOwnProperty(c)?a.N[d]={bc:!0,fc:this.ia[c]}:this.A.hasOwnProperty(c)&&(a.N[d]=URL.createObjectURL(this.A[c]))}}a.dc?this.s=
a.dc:(c=location.origin,this.s=("null"===c?"file:///":c)+location.pathname,c=this.s.lastIndexOf("/"),-1!==c&&(this.s=this.s.substr(0,c+1)));a.kc&&(this.aa=a.kc);c=new MessageChannel;this.V=c.port1;this.V.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Kb(d));this.U=new self.tb(this);await ja(this.U);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,
e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.u?await this.Gb(a,c.port2):await this.Fb(a,c.port2)}za(a){a=this.aa.hasOwnProperty(a)?this.aa[a]:a.endsWith("/workermain.js")&&this.aa.hasOwnProperty("workermain.js")?this.aa["workermain.js"]:"playable-ad"===this.i&&this.A.hasOwnProperty(a.toLowerCase())?this.A[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ta(a,c,d){if(a.startsWith("blob:"))return new Worker(a,
d);if("cordova"===this.i&&this.Ga)return a=await this.sa(d.ac?a:this.oa+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}B(){return Math.max(window.innerWidth,1)}v(){return Math.max(window.innerHeight,1)}Va(a){var c=this.s,d=location.href,e=this.B(),f=this.v(),g=window.devicePixelRatio,
h=b.O(),k=a.pc,v=window.cr_previewImageBlobs||this.A,ta=window.cr_previewProjectFileBlobs,va=window.cr_previewProjectFiles,wa=window.nc||"";a=a.mb;var xa=(new URLSearchParams(self.location.search)).has("debug"),J=this.U;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:v,previewProjectFileBlobs:ta,previewProjectFileSWUrls:va,swClientId:wa,exportType:a,isDebug:xa,ife:!!self.oc,jobScheduler:{inputPort:J.Fa,outputPort:J.Ja,
maxNumWorkers:J.Ub},supportedAudioFormats:da,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.oa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.oa+"opus.wasm.wasm",isFileProtocol:this.Ga,isiOSCordova:this.sb(),isiOSWebView:this.wa(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Gb(a,c){var d=this.za(a.jc);this.lb=await this.ta(d,this.s,{type:"module",name:"Runtime",ac:!0});this.j=document.createElement("canvas");this.j.style.display="none";d=this.j.transferControlToOffscreen();
document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let e=a.Ma||[],f=a.N;e=await Promise.all(e.map(g=>this.G(g)));f=await Promise.all(f.map(g=>this.G(g)));if("cordova"===this.i)for(let g=0,h=a.qa.length;g<h;++g){const k=a.qa[g],v=k[0];if(v===a.La||"scriptsInEvents.js"===v||v.endsWith("/scriptsInEvents.js"))k[1]=await this.G(v)}this.lb.postMessage(Object.assign(this.Va(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:d,
workerDependencyScripts:e,engineScripts:f,projectScripts:a.qa,mainProjectScript:a.La,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,d,...ka(this.U)]);this.ea=E.map(g=>new g(this));this.Ua();self.c3_callFunction=(g,h)=>{var k=this.Z;return k.g.ub(k.S,{name:g,params:h})};"preview"===this.i&&(self.goToLastErrorScript=()=>this.xa("runtime","go-to-last-error-script"))}async Fb(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=
this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.ea=E.map(g=>new g(this));this.Ua();var d=a.N.map(g=>"string"===typeof g?(new URL(g,this.s)).toString():g);Array.isArray(a.Ma)&&d.unshift(...a.Ma);d=await Promise.all(d.map(g=>this.G(g)));await Promise.all(d.map(g=>x(g)));d=self.C3_ProjectScriptsStatus;const e=a.La,f=a.qa;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.G(h),await x(h),"preview"!==this.i||d[g]||this.Ya(g,"main script did not run to completion")}catch(k){this.Ya(g,
k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.G(h),await x(h);"preview"===this.i&&"object"!==typeof self.lc.mc?(this.da(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Va(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:H}),this.Xa(),this.Ia=
self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ia,a))}Ya(a,c){this.da();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Xa(){this.da()}da(){const a=window.Zb;a&&(a.parentElement.removeChild(a),window.Zb=null)}async Ib(){const a=await la(this.U);return{outputPort:a,transferables:[a]}}Eb(){if(this.u)throw Error("not available in worker mode");
return this.Ia}xa(a,c,d,e,f){this.V.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}ub(a,c){const d=fa++,e=new Promise((f,g)=>{G.set(d,{resolve:f,reject:g})});this.V.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Jb(a);if("result"===c)this.Mb(a);else if("runtime-ready"===c)this.Nb();else if("alert-error"===c)this.da(),
alert(a.message);else if("creating-runtime"===c)this.Xa();else throw Error(`unknown message '${c}'`);}Jb(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.ca(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.ca(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.ca(f,!1,""+h)}):this.ca(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);
else console.warn(`[DOM] No event handlers for component '${c}'`)}ca(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.V.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Mb(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}h(a,c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static ra(a){if(E.includes(a))throw Error("DOM handler already added");
E.push(a)}Ua(){for(const a of this.ea)if("runtime"===a.S){this.Z=a;return}throw Error("cannot find runtime DOM handler");}Kb(a){this.xa("debugger","message",a)}Nb(){for(const a of this.ea)a.Na()}static O(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ia)}static Za(a){ia=!!a}xb(a){this.J.push(a);this.Ba()}Pb(a){a=this.J.indexOf(a);if(-1===a)throw Error("invalid callback");this.J.splice(a,1);this.J.length||this.Ta()}Ba(){-1===this.K&&this.J.length&&
(this.K=requestAnimationFrame(this.Vb))}Ta(){-1!==this.K&&(cancelAnimationFrame(this.K),this.K=-1)}Lb(){this.K=-1;for(const a of this.J)a();this.Ba()}F(a){this.Z.F(a)}D(a){this.Z.D(a)}Aa(){this.Z.Aa()}wb(){this.gb=!0}pb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}rb(a){return!this.pb(a)}async G(a){return"cordova"===this.i&&(a.startsWith("file:")||this.Ga&&this.rb(a))?(a.startsWith(this.s)&&(a=a.substr(this.s.length)),a=await this.sa(a),URL.createObjectURL(new Blob([a],
{type:"application/javascript"}))):a}async Hb(a){const c=a.filename;switch(a.as){case "text":return await this.nb(c);case "buffer":return await this.sa(c);default:throw Error("unsupported type");}}Oa(a){const c=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async nb(a){a=await this.Oa(a);return await ea(a)}ya(){if(C.length&&!(8<=D)){D++;var a=C.shift();this.Bb(a.filename,a.hc,a.$b)}}sa(a){return new Promise((c,
d)=>{C.push({filename:a,hc:e=>{D--;this.ya();c(e)},$b:e=>{D--;this.ya();d(e)}});this.ya()})}async Bb(a,c,d){try{const e=await this.Oa(a),f=await B(e);c(f)}catch(e){d(e)}}Qb(){var a={type:"ready"};if("windows-webview2"===this.i)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.i)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async Ab(){const a=[];for(const [c,d]of Object.entries(this.A))a.push(this.zb(c,
d));await Promise.all(a)}async zb(a,c){if("object"===typeof c)this.A[a]=new Blob([c.str],{type:c.type}),this.ia[a]=c.str;else{let d=await this.Db(c);d||(d=this.Cb(c));this.A[a]=d}}async Db(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Cb(a){a=this.Ob(a);return this.yb(a.data,
a.cc)}Ob(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{cc:a,data:d}}yb(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const I=self.ba;function ma(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const na=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},oa={dispatchUserScriptEvent:!0},L={dispatchRuntimeEvent:!0};
function pa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function qa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function M(b){b=URL.createObjectURL(b);try{return await qa(b)}finally{URL.revokeObjectURL(b)}}
function ra(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function sa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await M(b);var d=await ra(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await M(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await M(b)}
function N(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const ya=new Set(["input","textarea","datalist","select"]),za=new Set(["canvas","body","html"]);function O(b){za.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Aa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await M(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await sa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let P=!1;document.addEventListener("pause",()=>P=!0);document.addEventListener("resume",()=>P=!1);async function Ba(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ca(b){return await self.C3_GetSvgImageSize(b.blob)}
function Da(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ea(b){self.setTimeout(()=>{b.eb=!0},1E3);"cordova"===b.g.i?(document.addEventListener("pause",()=>Q(b,!0)),document.addEventListener("resume",()=>Q(b,!1))):document.addEventListener("visibilitychange",()=>Q(b,document.hidden));return{isSuspended:!(!document.hidden&&!P)}}
function Fa(b){b.ab||(b.ab=!0,window.addEventListener("deviceorientation",a=>{b.m||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.m||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Ga(b){b.$a||(b.$a=!0,window.addEventListener("devicemotion",a=>{if(!b.m){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Ha(b){await pa(b.url)}
function Ia(b,a){b.fb=a.message;-1===b.Ea&&(b.Ea=setTimeout(()=>{b.Ea=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.fb)},250))}function R(b){if(!b.m){var a=I.O();a&&"any"!==b.Ka&&Ja(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.B(),innerHeight:b.v()})}}function S(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:I.O(),innerWidth:b.B(),innerHeight:b.v()})}
function Q(b,a){a?b.g.Ta():b.g.Ba();l(b,"visibilitychange",{hidden:a})}function Ka(b,a,c){"Backspace"===c.key&&O(c);if(!b.m){var d=na.get(c.code)||c.code;m(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K)}}
function T(b,a,c,d){b.m||ma(c)||m(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.o,pageX:c.pageX,pageY:c.pageY+b.o,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function U(b){window!==window.top&&window.focus();La(b.target)&&document.activeElement&&!La(document.activeElement)&&document.activeElement.blur()}
function V(b,a,c){if(!b.m){if(b.X&&"pointermove"!==a){var d=b.X;d.T||(-1!==d.M&&(self.clearTimeout(d.M),d.M=-1),d.ga=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.W);m(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.o,pageX:c.pageX,pageY:c.pageY+b.o,movementX:(c.movementX||0)+b.la,movementY:(c.movementY||0)+b.ma,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||
0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);b.la=0;b.ma=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),T(b,d,c,oa),b.W=c.buttons)}}
function W(b,a,c){if(!b.m&&!ma(c)){var d=b.W;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");m(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.o,pageX:c.pageX,pageY:c.pageY+b.o,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},K);b.W=c.buttons;T(b,c.type,c,oa)}}
function X(b,a,c){if(!b.m)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];m(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.o,pageX:f.pageX,pageY:f.pageY+b.o,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
K)}}function Y(b,a,c){document.body.style.transform="";b.o=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.o=a))}}function Ma(b,a,c,d){const e=b.B(),f=b.v();b.L=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.O()}):10>d&&Na(b,e,f,d+1)}
function Na(b,a,c,d){-1!==b.L&&clearTimeout(b.L);b.L=setTimeout(()=>Ma(b,a,c,d),48)}
function Ja(b){b=b.Ka;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function La(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.ra(class extends self.ua{constructor(b){super(b,"runtime");this.hb=!0;this.L=-1;this.Ka="any";this.$a=this.ab=!1;this.C=null;this.m=!1;this.fb="";this.Ea=-1;this.H=this.X=null;this.ma=this.la=0;this.eb=!1;this.jb=b.B();this.ha=b.v();this.o=this.$=0;b.h("canvas","update-size",d=>{var e=this.g;e.gb||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",this.hb&&(e.style.display="",this.hb=!1))});b.h("runtime",
"invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","raster-svg-image",d=>Ba(d));b.h("runtime","get-svg-image-size",d=>Ca(d));b.h("runtime","set-target-orientation",d=>{this.Ka=d.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime","post-to-debugger",d=>Da(d));b.h("runtime","go-to-script",d=>
Da(d));b.h("runtime","before-start-ticking",()=>Ea(this));b.h("runtime","debug-highlight",d=>{if(d.show){this.C||(this.C=document.createElement("div"),this.C.id="inspectOutline",document.body.appendChild(this.C));var e=this.C;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.C&&(this.C.style.display="none")});b.h("runtime","enable-device-orientation",()=>Fa(this));b.h("runtime","enable-device-motion",
()=>Ga(this));b.h("runtime","add-stylesheet",d=>Ha(d));b.h("runtime","alert",d=>{alert(d.message)});b.h("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",d=>{this.m=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.g.j.style.display="";this.g.wb()});b.h("runtime","export-to-video-progress",
d=>Ia(this,d));b.h("runtime","exported-to-video",d=>{window.Yb({type:"exported-video",blob:d.blob,time:d.time})});b.h("runtime","exported-to-image-sequence",d=>{window.Yb({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||N(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",O);window.addEventListener("gesturehold",
O);c.addEventListener("selectstart",O);c.addEventListener("gesturehold",O);window.addEventListener("touchstart",O,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",O,{passive:!1}),c.addEventListener("pointerdown",O)):c.addEventListener("touchstart",O);this.W=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Aa,{passive:!1});window.addEventListener("wheel",Aa,{passive:!1});window.addEventListener("resize",
()=>{a:{if(!this.m){var d=this.B();var e=this.v();if(this.g.va()){if(this.eb){if(this.jb===d&&e<this.ha){this.$=this.ha-e;Y(this,this.ha,this.$);d=void 0;break a}0<this.$&&(this.$=0,Y(this,e,this.$))}this.jb=d;this.ha=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.O()});this.g.wa()&&(-1!==this.L&&clearTimeout(this.L),Ma(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>R(this));window.addEventListener("webkitfullscreenchange",
()=>R(this));window.addEventListener("mozfullscreenchange",()=>R(this));window.addEventListener("fullscreenerror",d=>S(this,d));window.addEventListener("webkitfullscreenerror",d=>S(this,d));window.addEventListener("mozfullscreenerror",d=>S(this,d));if(b.wa())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;
if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):N(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(I.Za(!0),R(this)):"exited-fullscreen"===d?(I.Za(!1),R(this)):console.warn("Unknown wrapper message: ",d)};this.I=new Set;this.ja=new WeakSet;this.Tb=!1}Na(){window.addEventListener("focus",()=>{l(this,"window-focus",
null,L)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}l(this,"window-blur",{parentHasFocus:a},L);this.W=0});window.addEventListener("focusin",a=>{a=a.target;(ya.has(a.tagName.toLowerCase())||N(a))&&l(this,"keyboard-blur",null,L)});window.addEventListener("keydown",a=>Ka(this,"keydown",a));window.addEventListener("keyup",a=>Ka(this,"keyup",a));window.addEventListener("dblclick",a=>T(this,"dblclick",a,K));window.addEventListener("wheel",
a=>{this.m||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.o,pageX:a.pageX,pageY:a.pageY+this.o,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{U(a);V(this,"pointerdown",a)}),this.g.u&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.X=new self.vb(()=>{V(this,"pointermove",this.H);this.H=null}),this.X.cb=!0,window.addEventListener("pointerrawupdate",
a=>{this.H&&(this.la+=this.H.movementX||0,this.ma+=this.H.movementY||0);this.H=a;a=this.X;if(-1===a.M){var c=Date.now(),d=c-a.ga,e=a.Sb;d>=e&&a.cb?(a.ga=c,a.T=!0,a.bb(),a.T=!1):a.M=self.setTimeout(a.Xb,Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>V(this,"pointermove",a)),window.addEventListener("pointerup",a=>V(this,"pointerup",a)),window.addEventListener("pointercancel",a=>V(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{U(a);W(this,"pointerdown",a)}),window.addEventListener("mousemove",
a=>W(this,"pointermove",a)),window.addEventListener("mouseup",a=>W(this,"pointerup",a)),window.addEventListener("touchstart",a=>{U(a);X(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>X(this,"pointermove",a)),window.addEventListener("touchend",a=>X(this,"pointerup",a)),window.addEventListener("touchcancel",a=>X(this,"pointercancel",a)));const b=()=>this.Aa();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.g.qb()&&!this.g.va()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Y(this,this.v(),navigator.virtualKeyboard.boundingRect.height)}))}B(){return this.g.B()}v(){return this.g.v()}Aa(){var b=[...this.I];this.I.clear();if(!this.Tb)for(const a of b)(b=a.play())&&b.catch(()=>{this.ja.has(a)||this.I.add(a)})}F(b){if("function"!==typeof b.play)throw Error("missing play function");
this.ja.delete(b);let a;try{a=b.play()}catch(c){this.I.add(b);return}a&&a.catch(()=>{this.ja.has(b)||this.I.add(b)})}D(b){this.I.delete(b);this.ja.add(b)}});"use strict";async function ja(b){if(b.Rb)throw Error("already initialised");b.Rb=!0;var a=b.na.za("dispatchworker.js");b.Da=await b.na.ta(a,b.R,{name:"DispatchWorker"});a=new MessageChannel;b.Fa=a.port1;b.Da.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Ja=await la(b)}function ka(b){return[b.Fa,b.Ja]}
async function la(b){const a=b.ib.length;var c=b.na.za("jobworker.js");c=await b.na.ta(c,b.R,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Da.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.ib.push(c);return e.port1}
self.tb=class{constructor(b){this.na=b;this.R=b.s;this.R="preview"===b.i?this.R+"workers/":this.R+b.oa;this.Ub=Math.min(navigator.hardwareConcurrency||2,16);this.Da=null;this.ib=[];this.Ja=this.Fa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ba({ic:!0,jc:"workermain.js",N:["scripts/c3runtime.js"],qa:[],La:"",ec:"scripts/",Ma:[],mb:"html5"}));"use strict";
self.ba.ra(class extends self.ua{constructor(b){super(b,"mouse");p(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.g.j.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{l(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{l(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function Oa(b,a){b.Ha=a.isInWorker;a=document.createElement("video");b.pa=!!a.requestVideoFrameCallback&&!b.g.va();const c=!!self.createImageBitmap;b.Y=b.Ha||c;return{postImageBitmaps:b.Y,supportedFormats:{"video/webm":!!a.canPlayType("video/webm"),"video/ogg":!!a.canPlayType("video/ogg"),"video/mp4":!!a.canPlayType("video/mp4")}}}
async function Pa(b,a){if(!b.Ca.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>Pa(b,a));try{const c=a.c3_sequenceNumber++,d=await createImageBitmap(a);c>a.c3_lastFrameSequence&&(a.c3_imageBitmap=d,a.c3_lastFrameSequence=c)}catch(c){}}}function Z(b,a,c,d){b.Ca.has(a)||q(b,"playback-event",c,{type:d})}
self.ba.ra(class extends self.ob{constructor(b){super(b);this.Y=this.pa=this.Ha=this.P=!1;this.ka=this.Wb=0;this.Ca=new WeakSet;n(this,"init",a=>Oa(this,a));r(this,"play",a=>{this.F(a)});r(this,"pause",a=>{this.D(a);a.pause()});r(this,"set-source",(a,c)=>{a.src=c.src;a.load()});r(this,"set-playback-time",(a,c)=>{try{a.currentTime=c.time}catch(d){console.error("[Video] Exception setting playback time: ",d)}});r(this,"set-playback-rate",(a,c)=>{try{a.playbackRate=c.rate}catch(d){console.error("[Video] Exception setting playback rate: ",
d)}});r(this,"set-looping",(a,c)=>{a.loop=c.isLooping});r(this,"set-muted",(a,c)=>{a.muted=c.isMuted});r(this,"set-volume",(a,c)=>{a.volume=c.volume});self.C3Video_GetElement=a=>this.l.get(a)}F(b){this.g.F(b);this.Y&&this.pa&&-1===b.c3_rvfcId&&(b.c3_rvfcId=b.requestVideoFrameCallback(()=>Pa(this,b)))}D(b){this.g.D(b);this.Y&&this.pa&&-1!==b.c3_rvfcId&&(b.cancelVideoFrameCallback(b.c3_rvfcId),b.c3_rvfcId=-1)}Pa(b,a){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=!0;
c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",()=>Z(this,c,b,0));c.addEventListener("canplaythrough",()=>Z(this,c,b,1));c.addEventListener("ended",()=>Z(this,c,b,2));c.addEventListener("error",()=>Z(this,c,b,3));c.addEventListener("loadstart",()=>Z(this,c,b,4));c.addEventListener("playing",()=>Z(this,c,b,5));c.addEventListener("pause",()=>Z(this,c,b,6));c.addEventListener("stalled",()=>Z(this,c,b,7));const d=a.autoplay;0===d?(c.autoplay=
!1,c.preload="none"):1===d?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;a.src&&(c.src=a.src);2===d&&this.F(c);this.ka++;this.fa||(this.g.xb(this.kb),this.fa=!0);return c}Sa(){}Qa(b){this.D(b);b&&!b.paused&&!b.ended&&0<b.currentTime&&b.pause();b.src="";this.ka=Math.max(this.ka-1,0);0===this.ka&&this.fa&&(this.g.Pb(this.kb),this.fa=!1);this.Ca.add(b)}Ra(){const b={},a={sequenceNumber:this.Wb++,videoData:b},c=[],d=[];for(const [e,f]of this.l.entries()){const g={currentTime:f.currentTime,playbackRate:f.playbackRate,
duration:f.duration,videoWidth:f.videoWidth,videoHeight:f.videoHeight};if(this.Y)if(this.pa){const h=f.c3_imageBitmap;f.c3_imageBitmap=null;(g.imageBitmap=h)&&c.push(h)}else d.push(createImageBitmap(f).then(h=>{g.imageBitmap=h;c.push(h)}).catch(()=>{g.imageBitmap=null}));b[e.toString()]=g}Promise.all(d).then(()=>{this.Ha?l(this,"state",a,!1,c):m(this,"state",a)})}});
