function l(b,a,c,d){b.v.Db(b.jb,a,c,d,void 0)}function m(b,a,c,d){b.v.ca?l(b,a,c,d):b.v.ue()._OnMessageFromDOM({type:"event",component:b.jb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.v.C(b.jb,a,c)}function t(b,a){for(const [c,d]of a)p(b,c,d)}function u(b){b.Ob||(b.v.dd(b.Od),b.Ob=!0)}window.ab=class{constructor(b,a){this.v=b;this.jb=a;this.Ob=!1;this.Od=()=>this.Ba()}Wc(){}Ba(){}};
window.df=class{constructor(){this.Tc=-1}j(){-1!==this.Tc&&(self.clearTimeout(this.Tc),this.Tc=-1)}};"use strict";function aa(b,a){p(b,"get-element",c=>{const d=v(b,c.elementId);return a(d,c)})}function v(b,a){b=b.Mb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.qd}
window.cf=class extends self.ab{constructor(b,a){super(b,a);this.Mb=new Map;this.zc=!0;t(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=v(this,c);this.zc&&d.parentElement.removeChild(d);this.Mb.delete(c)}],["set-visible",c=>{if(this.zc){var d=this.Mb.get(c.elementId),e=d.qd;d.wd?e.style.display=c.isVisible?"":"none":d.Ke=!!c.isVisible}}],["update-position",c=>{if(this.zc){var d=this.Mb.get(c.elementId),e=d.qd;e.style.left=c.left+"px";e.style.top=c.top+
"px";e.style.width=c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.wd||(d.wd=!0,d.Ke&&(e.style.display=""))}}],["update-state",c=>{v(this,c.elementId);throw Error("required override");}],["focus",c=>{const d=v(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=v(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{v(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",
c=>{v(this,c.elementId).removeAttribute(c.name)}]]);aa(this,c=>c)}};"use strict";const ba=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),w=/android/i.test(navigator.userAgent),ca=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let da=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Te?new Promise(c=>{const d="c3_resolve_"+da;++da;self[d]=c;a.textContent=b.Xe+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ea=!1,fa=!1;function ha(){if(!ea){try{new Worker("blob://",{get type(){fa=!0}})}catch(b){}ea=!0}return fa}let z=new Audio;
const ia={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}
function ka(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let D=0;window.RealFile=window.File;const F=[],G=new Map,la=new Map;let oa=0;const pa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");pa.push(b)};const qa=new Set(["cordova","playable-ad","instant-games"]);let ra=!1;
window.gb=class b{constructor(a){this.ca=a.Ze;this.va=null;this.ba="";this.Xa=a.We;this.zb={};this.Qa=this.ta=null;this.Lb=[];this.I=this.wa=null;this.Hc=!1;this.td=0;this.ob=null;this.Wa=-1;this.Oe=()=>this.Be();this.Va=[];this.B=a.Pd;this.Pb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ha()||(this.ca=!1);this.ca&&ca&&(this.ca=!1);if("playable-ad"===this.B||"instant-games"===this.B)this.ca=!1;if("cordova"===this.B&&this.ca)if(w){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.Sb=this.qa=null;"html5"!==this.B||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.xe(c));this.C("runtime","create-job-worker",()=>this.ye());"cordova"===this.B?document.addEventListener("deviceready",
()=>this.gd(a)):this.gd(a)}j(){this.qc();this.va&&(this.va=this.va.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Qa&&(this.Qa.j(),this.Qa=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}je(){return ba&&"cordova"===this.B}mc(){const a=navigator.userAgent;return ba&&qa.has(this.B)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}he(){return w}ad(){return w&&qa.has(this.B)}async gd(a){"macos-wkwebview"===this.B&&this.Ge();if("playable-ad"===this.B){this.qa=
self.c3_base64files;this.Sb={};await this.qe();for(let d=0,e=a.Za.length;d<e;++d){var c=a.Za[d];this.Sb.hasOwnProperty(c)?a.Za[d]={Te:!0,Xe:this.Sb[c]}:this.qa.hasOwnProperty(c)&&(a.Za[d]=URL.createObjectURL(this.qa[c]))}a.ec=[]}if("nwjs"===this.B&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.dd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Ve?this.ba=a.Ve:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=
this.ba.substr(0,c+1)));a.af&&(this.zb=a.af);c=new MessageChannel;this.va=c.port1;this.va.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ae(d));this.ob=new self.ke(this);await sa(this.ob);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.ca?await this.we(a,c.port2):await this.ve(a,c.port2)}sc(a){a=this.zb.hasOwnProperty(a)?this.zb[a]:a.endsWith("/workermain.js")&&this.zb.hasOwnProperty("workermain.js")?this.zb["workermain.js"]:"playable-ad"===this.B&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async hc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.B&&this.Pb)return a=await this.Bb(d.Se?a:this.Xa+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}oa(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}fd(a){var c=this.ba,d=location.href,e=this.oa(),f=this.ha(),g=window.devicePixelRatio,h=b.eb(),k=a.hf,n=window.cr_previewImageBlobs||this.qa,q=window.cr_previewProjectFileBlobs,A=window.cr_previewProjectFiles,x=window.ff||
"";a=a.Pd;var r=(new URLSearchParams(self.location.search)).has("debug"),B=this.ob;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:n,previewProjectFileBlobs:q,previewProjectFileSWUrls:A,swClientId:x,exportType:a,isDebug:r,ife:!!self.gf,jobScheduler:{inputPort:B.Gc,outputPort:B.Oc,maxNumWorkers:B.Le},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Xa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Xa+"opus.wasm.wasm",isFileProtocol:this.Pb,isiOSCordova:this.je(),isiOSWebView:this.mc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async we(a,c){const d=this.sc(a.$e);"preview"===this.B?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const n=q=>{this.ta.removeEventListener("message",n);q.data&&"ok"===q.data.type?h():k()};this.ta.addEventListener("message",n);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,
this.ba)).toString()})})):this.ta=await this.hc(d,this.ba,{type:"module",name:"Runtime",Se:!0});this.I=document.createElement("canvas");this.I.style.display="none";const e=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=this.I;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.ec||[],g=a.Za;f=await Promise.all(f.map(h=>this.La(h)));g=await Promise.all(g.map(h=>this.La(h)));if("cordova"===this.B)for(let h=0,k=a.dc.length;h<k;++h){const n=
a.dc[h],q=n[0];if(q===a.Uc||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))n[1]=await this.La(q)}this.ta.postMessage(Object.assign(this.fd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.dc,mainProjectScript:a.Uc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ta(this.ob)]);this.Lb=F.map(h=>new h(this));this.ed();ua(this.wa);self.c3_callFunction=(h,k)=>{var n=this.wa;return n.v.cd(n.jb,"js-invoke-function",
{name:h,params:k},void 0,void 0)};"preview"===this.B&&(self.goToLastErrorScript=()=>this.Db("runtime","go-to-last-error-script"))}async ve(a,c){this.I=document.createElement("canvas");this.I.style.display="none";document.body.appendChild(this.I);window.c3canvas=this.I;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Lb=F.map(g=>new g(this));this.ed();var d=a.Za.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);Array.isArray(a.ec)&&d.unshift(...a.ec);d=await Promise.all(d.map(g=>
this.La(g)));await Promise.all(d.map(g=>y(g)));d=self.C3_ProjectScriptsStatus;const e=a.Uc,f=a.dc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.La(h),await y(h),"preview"!==this.B||d[g]||this.jd(g,"main script did not run to completion")}catch(k){this.jd(g,k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.La(h),await y(h);"preview"===this.B&&"object"!==typeof self.bf.ef?(this.Hb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.fd(a),{isInWorker:!1,messagePort:c,canvas:this.I,runOnStartupFunctions:pa}),ua(this.wa),this.hd(),this.Qa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Qa,a))}jd(a,c){this.Hb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}hd(){this.Hb()}Hb(){const a=
window.Qe;a&&(a.parentElement.removeChild(a),window.Qe=null)}async ye(){const a=await va(this.ob);return{outputPort:a,transferables:[a]}}ue(){if(this.ca)throw Error("not available in worker mode");return this.Qa}Db(a,c,d,e,f){this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}cd(a,c,d,e,f){const g=oa++,h=new Promise((k,n)=>{la.set(g,{resolve:k,reject:n})});this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.ze(a);if("result"===c)this.Ce(a);else if("runtime-ready"===c)this.De();else if("alert-error"===c)this.Hb(),alert(a.message);else if("creating-runtime"===c)this.hd();else throw Error(`unknown message '${c}'`);}ze(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Gb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Gb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Gb(f,!1,""+h)}):this.Gb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Gb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.va.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ce(a){const c=a.responseId,d=a.isOk;a=a.result;const e=la.get(c);d?e.resolve(a):e.reject(a);la.delete(c)}C(a,
c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Ab(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}ed(){for(const a of this.Lb)if("runtime"===a.jb){this.wa=a;return}throw Error("cannot find runtime DOM handler");}Ae(a){this.Db("debugger","message",a)}De(){for(const a of this.Lb)a.Wc()}static eb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
ra)}static kd(a){ra=!!a}dd(a){this.Va.push(a);this.xc()}Fe(a){a=this.Va.indexOf(a);if(-1===a)throw Error("invalid callback");this.Va.splice(a,1);this.Va.length||this.qc()}xc(){-1===this.Wa&&this.Va.length&&(this.Wa=requestAnimationFrame(this.Oe))}qc(){-1!==this.Wa&&(cancelAnimationFrame(this.Wa),this.Wa=-1)}Be(){this.Wa=-1;for(const a of this.Va)a();this.xc()}Ca(a){this.wa.Ca(a)}Ka(a){this.wa.Ka(a)}wc(){this.wa.wc()}Fb(a){this.wa.Fb(a)}ie(){return!!ia["audio/webm; codecs=opus"]}async He(a){a=await this.cd("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}me(a){this.Hc=!0;this.td=a}ge(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}bd(a){return!this.ge(a)}async La(a){return"cordova"===this.B&&(a.startsWith("file:")||this.Pb&&this.bd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Bb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async xe(a){const c=a.filename;switch(a.as){case "text":return await this.fe(c);
case "buffer":return await this.Bb(c);default:throw Error("unsupported type");}}Zc(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async fe(a){a=await this.Zc(a);return await ja(a)}rc(){if(C.length&&!(8<=D)){D++;var a=C.shift();this.re(a.filename,a.Ye,a.Re)}}Bb(a){return new Promise((c,d)=>{C.push({filename:a,Ye:e=>{D--;this.rc();c(e)},Re:e=>{D--;this.rc();d(e)}});this.rc()})}async re(a,c,d){try{const e=
await this.Zc(a),f=await ka(e);c(f)}catch(e){d(e)}}Ge(){var a={type:"ready"};if("windows-webview2"===this.B)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.B)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async qe(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.pe(c,d));await Promise.all(a)}async pe(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),
this.Sb[a]=c.str;else{let d=await this.te(c);d||(d=this.se(c));this.qa[a]=d}}async te(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}se(a){a=this.Ee(a);return this.oe(a.data,a.Ue)}Ee(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+
1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Ue:a,data:d}}oe(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const H=self.gb;
function wa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const xa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},ya={dispatchUserScriptEvent:!0},za={dispatchRuntimeEvent:!0};
function Aa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ba(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await Ba(b)}finally{URL.revokeObjectURL(b)}}
function Ca(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Da(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await Ca(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Ea(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Fa=new Set(["input","textarea","datalist","select"]),Ga=new Set(["canvas","body","html"]);function K(b){b.target.tagName&&Ga.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ha(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Da(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ia=!1;document.addEventListener("pause",()=>Ia=!0);document.addEventListener("resume",()=>Ia=!1);function ua(b){b.sd=!0;b.Lc=b.v.oa();b.pb=b.v.ha()}async function Ja(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ka(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function La(b){return await self.C3_GetSvgImageSize(b.blob)}function Ma(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Na(b){self.setTimeout(()=>{b.rd=!0},1E3);"cordova"===b.v.B?(document.addEventListener("pause",()=>Oa(b,!0)),document.addEventListener("resume",()=>Oa(b,!1))):document.addEventListener("visibilitychange",()=>Oa(b,document.hidden));return{isSuspended:!(!document.hidden&&!Ia)}}
function Pa(b){b.md||(b.md=!0,window.addEventListener("deviceorientation",a=>{b.$||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Qa(b){b.ld||(b.ld=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Ra(b){await Aa(b.url)}
function Sa(b,a){b.ud=a.message;-1===b.Cc&&(b.Cc=setTimeout(()=>{b.Cc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.ud)},250))}function L(b){if(!b.$){var a=H.eb();a&&"any"!==b.Rc&&Ta(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ha()})}}function Ua(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:H.eb(),innerWidth:b.oa(),innerHeight:b.ha()})}
function Oa(b,a){a?b.v.qc():b.v.xc();l(b,"visibilitychange",{hidden:a})}function Va(b,a,c){"Backspace"===c.key&&K(c);if(!b.$){var d=xa.get(c.code)||c.code;m(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function Wa(b,a,c,d){b.$||wa(c)||m(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Xa(b){window!==window.top&&window.focus();Ya(b.target)&&document.activeElement&&!Ya(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.ub);m(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Wa(b,d,c,ya),b.ub=c.buttons)}}
function Za(b,a,c){if(!b.$&&!wa(c)){var d=b.ub;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");m(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.ub=c.buttons;Wa(b,c.type,c,ya)}}
function N(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];m(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function bb(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function cb(b,a,c,d){const e=b.oa(),f=b.ha();b.Ya=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.eb()}):10>d&&db(b,e,f,d+1)}
function db(b,a,c,d){-1!==b.Ya&&clearTimeout(b.Ya);b.Ya=setTimeout(()=>cb(b,a,c,d),48)}
function Ta(b){b=b.Rc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ya(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.Ab(class extends self.ab{constructor(b){super(b,"runtime");this.Ad=!0;this.sd=!1;this.Ya=-1;this.Rc="any";this.ld=this.md=!1;this.ac=document.createElement("div");this.ac.className="c3-screen-reader-text";this.ac.setAttribute("aria-live","polite");document.body.appendChild(this.ac);this.Fa=null;this.$=!1;this.ud="";this.Cc=-1;this.rd=!1;this.Lc=b.oa();this.pb=b.ha();this.da=this.yb=0;b.C("canvas","update-size",d=>{var e=this.v;e.Hc||(e=e.I,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Ad&&(e.style.display="",this.Ad=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Ja(d));b.C("runtime","raster-svg-image",d=>Ka(d));b.C("runtime","get-svg-image-size",
d=>La(d));b.C("runtime","set-target-orientation",d=>{this.Rc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Ma(d));b.C("runtime","go-to-script",d=>Ma(d));b.C("runtime","before-start-ticking",()=>Na(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Fa||(this.Fa=document.createElement("div"),this.Fa.id="inspectOutline",document.body.appendChild(this.Fa));var e=this.Fa;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Fa&&(this.Fa.style.display="none")});b.C("runtime","enable-device-orientation",()=>Pa(this));b.C("runtime","enable-device-motion",()=>Qa(this));b.C("runtime","add-stylesheet",d=>Ra(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>{alert(d.message)});
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ac.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.I.style.display="";this.v.me(d.duration)});b.C("runtime","export-to-video-progress",d=>Sa(this,d));b.C("runtime","exported-to-video",d=>{window.Pe({type:"exported-video",
blob:d.blob,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Pe({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ea(e)||d.preventDefault()});const c=b.I;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",K);window.addEventListener("touchstart",
K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",K);this.ub=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ha,{passive:!1});window.addEventListener("wheel",Ha,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.sd){var d=this.oa();var e=this.ha();if(this.v.ad()){if(this.rd){if(this.Lc===d&&
e<this.pb){this.yb=this.pb-e;bb(this,this.pb,this.yb);d=void 0;break a}0<this.yb&&(this.yb=0,bb(this,e,this.yb))}this.Lc=d;this.pb=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.eb()});this.v.mc()&&(-1!==this.Ya&&clearTimeout(this.Ya),cb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",()=>L(this));window.addEventListener("mozfullscreenchange",()=>
L(this));window.addEventListener("fullscreenerror",d=>Ua(this,d));window.addEventListener("webkitfullscreenerror",d=>Ua(this,d));window.addEventListener("mozfullscreenerror",d=>Ua(this,d));if(b.mc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ea(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(H.kd(!0),L(this)):"exited-fullscreen"===d?(H.kd(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Ra=new Set;this.Ub=new WeakSet;this.ua=!1}Wc(){window.addEventListener("focus",()=>{l(this,"window-focus",null,za)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}l(this,"window-blur",{parentHasFocus:a},za);this.ub=0});window.addEventListener("focusin",a=>{a=a.target;(Fa.has(a.tagName.toLowerCase())||Ea(a))&&l(this,"keyboard-blur",null,za)});window.addEventListener("keydown",a=>Va(this,"keydown",a));window.addEventListener("keyup",a=>Va(this,"keyup",a));window.addEventListener("dblclick",a=>Wa(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.$||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,
deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Xa(a);M(this,"pointerdown",a)}),this.v.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Xa(a);Za(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>Za(this,"pointermove",a)),window.addEventListener("mouseup",a=>Za(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Xa(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=
()=>this.wc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.he()&&!this.v.ad()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{bb(this,this.ha(),navigator.virtualKeyboard.boundingRect.height)}))}oa(){return this.v.oa()}ha(){return this.v.ha()}wc(){var b=
[...this.Ra];this.Ra.clear();if(!this.ua)for(const a of b)(b=a.play())&&b.catch(()=>{this.Ub.has(a)||this.Ra.add(a)})}Ca(b){if("function"!==typeof b.play)throw Error("missing play function");this.Ub.delete(b);let a;try{a=b.play()}catch(c){this.Ra.add(b);return}a&&a.catch(()=>{this.Ub.has(b)||this.Ra.add(b)})}Ka(b){this.Ra.delete(b);this.Ub.add(b)}Fb(b){this.ua=!!b}});"use strict";
async function sa(b){if(b.Ie)throw Error("already initialised");b.Ie=!0;var a=b.xa.sc(("playable-ad"===b.xa.B?b.xa.Xa:"")+"dispatchworker.js");b.Bc=await b.xa.hc(a,b.ib,{name:"DispatchWorker"});a=new MessageChannel;b.Gc=a.port1;b.Bc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Oc=await va(b)}function ta(b){return[b.Gc,b.Oc]}
async function va(b){const a=b.Cd.length;var c=b.xa.sc(("playable-ad"===b.xa.B?b.xa.Xa:"")+"jobworker.js");c=await b.xa.hc(c,b.ib,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Bc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Cd.push(c);return e.port1}
self.ke=class{constructor(b){this.xa=b;this.ib=b.ba;this.ib="preview"===b.B?this.ib+"workers/":this.ib+b.Xa;this.Le=Math.min(navigator.hardwareConcurrency||2,16);this.Bc=null;this.Cd=[];this.Oc=this.Gc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.gb({Ze:!1,$e:"workermain.js",Za:["scripts/c3runtime.js"],dc:[],Uc:"",We:"scripts/",ec:[],Pd:"html5"}));"use strict";const eb=180/Math.PI;
async function fb(b,a){if(a.isiOSCordova||a.isSafari)b.Xb=!0;b.Sc=a.timeScaleMode;b.Hd=["equalpower","HRTF","soundfield"][a.panningModel];b.pd=["linear","inverse","exponential"][a.distanceModel];b.Id=a.refDistance;b.Gd=a.maxDistance;b.Kd=a.rolloffFactor;if(b.v.Hc)b.Xb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.td)});else{var c={latencyHint:a.latencyHint};b.Nd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");hb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&hb(b);l(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Na=b.g.createGain();b.Na.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
O(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function ib(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,n=a.pos,q=a.panning,A=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Dd=g.slice(0);jb(b,g);try{b.R=await kb(b,c,d,e,g,f);if(q){P(b.R,!0);var r=b.R,B=q.innerAngle,ma=q.outerAngle,na=q.outerGain;if(r.nb){lb(r,q.x,q.y,q.z,q.angle);var E=self.$a.ne;r.ra[0]!==E(B)&&
(r.ra[0]=E(B),r.F.coneInnerAngle=E(B));r.ra[1]!==E(ma)&&(r.ra[1]=E(ma),r.F.coneOuterAngle=E(ma));r.ra[2]!==na&&(r.ra[2]=na,r.F.coneOuterGain=na)}q.hasOwnProperty("uid")&&(b.R.pa=q.uid)}else"number"===typeof A&&0!==A?(Q(b.R,!0),mb(b.R,A)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,k,n,x)}catch(Ab){console.error("[Construct] Audio: error starting playback: ",Ab);return}finally{c=g.join(" ");d=b.wb.get(c);if(!d)throw Error("expected pending tag");d.Vc--;0===d.Vc&&(d.resolve(),b.wb.delete(c))}u(b)}
async function nb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await ob(b,c);for(const q of R(b,c)){c=q;var f=d,g=e,h=a;if(!c.Pa){var k=c.G.gain;k.cancelScheduledValues(0);var n=c.s.g.currentTime;g=n+g;k.setValueAtTime(k.value,n);k.linearRampToValueAtTime(f,g);c.Ia=f;c.Oa=g;c.Md=h}}S(b)}async function pb(b,a){const c=a.tags;a=a.rate;await ob(b,c);for(const d of R(b,c))b=d,b.la!==a&&(b.la=a,b.Da())}
async function qb(b,a){const c=a.tags;a=a.pos;await ob(b,c);for(const d of R(b,c))d.nc(a)}async function rb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await kb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function sb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function tb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.Vd(b,...e);else if("delay"===c)d=new self.Td(b,...e);else if("convolution"===c){var g=d=new self.Sd(b,f.ia,...e),h=a.bufferType;g.nd=a.bufferOriginalUrl;g.od=h}else if("flanger"===c)d=new self.Wd(b,...e);else if("phaser"===
c)d=new self.Yd(b,...e);else if("gain"===c)d=new self.Xd(b,...e);else if("stereopan"===c)d=new self.$d(b,...e);else if("tremolo"===c)d=new self.ae(b,...e);else if("ringmod"===c)d=new self.Zd(b,...e);else if("distortion"===c)d=new self.Ud(b,...e);else if("compressor"===c)d=new self.Rd(b,...e);else if("analyser"===c)d=new self.Qd(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let n=g.ka.get(h);n||(n=[],g.ka.set(h,n));d.zd=n.length;d.Qc=h;n.push(d);ub(g,h)}vb(b)}
async function wb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.za()&&1===c||!e.za()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ka.values())for(const g of f)g.j();b.ka.clear();b.bc=a.timeScale;b.Dc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.ua=a.isSilent;b.v.Fb(b.ua);b.Tb=a.masterVolume;b.Na.gain.value=
b.Tb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>tb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>xb(b,f,c)));S(b)}
async function yb(b,a){try{const c=b.g.suspend(a.time);b.yd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Db("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>zb(d)),b.yd=!0);await c}catch(c){zb(c)}}
function hb(b){b.Nb||(b.Fc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Nb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ja)if(g.cb()===c)return await Bb(g),g;if(f)return null;if(e&&(b.Xb||b.xd)){f=0;for(let h=0,k=b.ja.length;h<k;++h)g=b.ja[h],b.ja[f]=g,g.za()?g.j():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.Nd;e&&f&&(b.xd=!0);c=!e||b.Xb||f?new self.de(b,a,c,d,e,f):new self.be(b,a,c,d,e);b.ja.push(c);await Bb(c);b.Fd.has(a)||(l(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.Fd.add(a));return c}
function Cb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Db(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.na()}function ub(b,a){a=a.toLowerCase();let c=b.na();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.na()):e.U(d[f+1].N())}}for(const f of Eb(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Ga&&b.Mc===a&&(b.Ga.disconnect(),b.Ga.connect(c))}
function*Eb(b,a){if(a)for(const c of b.H)Cb(0<c.ma.length?c.ma[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Fb(b,a,c){return c?b.v.He(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Gb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.ma;var c=a;for(const e of c){c=!1;for(const f of b)if(Cb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function kb(b,a,c,d,e,f){for(const g of b.H)if(g.cb()===c&&(g.fc()||f))return g.ma=e,g;a=await O(b,a,c,d,f);e="html5"===a.yc?new self.ce(a.s,a,e):new self.ee(a.s,a,e);b.H.push(e);return e}
function jb(b,a){a=a.join(" ");let c=b.wb.get(a);if(!c){let d=null;c={Vc:0,promise:new Promise(e=>d=e),resolve:d};b.wb.set(a,c)}c.Vc++}function ob(b,a){return(b=b.wb.get((0===a.length?b.Dd:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Ma.size)u(b);else for(const a of b.H)if(!a.J&&!a.O()){u(b);break}}function Hb(b,a,c,d){l(b,"trigger",{type:a,tags:c,aiid:d})}function vb(b){b.Ic||(b.Ic=!0,Promise.resolve().then(()=>Ib(b)))}
function Ib(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.bb());l(b,"fxstate",{fxstate:a});b.Ic=!1}
async function xb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,n=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await kb(b,d,e,f,h,g)}catch(A){console.error("[Construct] Audio: error loading audio state: ",A);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],f=d.orient,b.Sa[0]=f[0],b.Sa[1]=f[1],b.Sa[2]=f[2],e.setPosition(...b.Ta),e.setOrientation(...b.Sa),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),mb(b,d));c.Play(k,n,q,0);a.isPlaying||c.fb();c.uc(a)}}}function zb(b){console.error("[Audio] Offline rendering error: ",b)}
self.$a=class extends self.ab{constructor(b){super(b,"audio");this.Na=this.g=null;this.Nb=this.Fc=!1;this.ya=()=>{if(!this.Fc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Nb&&(this.Fc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Nb=!1)}};this.ja=[];this.H=[];this.R=null;this.Dd=[];this.Fd=new Set;this.Ed=-1;this.wb=new Map;this.Tb=1;this.ua=!1;this.Sc=0;this.bc=1;this.Dc=0;this.Hd="HRTF";this.pd="inverse";this.Id=600;this.Gd=1E4;this.Kd=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.xd=this.Xb=!1;this.Nd=this.v.ie();this.ka=new Map;this.Ma=new Set;this.yd=this.Ic=!1;this.Mc="";this.Ga=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ga&&this.Ga.disconnect();this.Mc=c.toLowerCase();this.Ga=this.g.createMediaStreamSource(a);
this.Ga.connect(Db(this,this.Mc))};this.Kb=null;self.C3Audio_GetOutputStream=()=>{this.Kb||(this.Kb=this.g.createMediaStreamDestination(),this.Na.connect(this.Kb));return this.Kb.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>fb(this,a)],["play",a=>ib(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Aa()}],["stop-all",()=>{for(const a of this.H)a.Aa()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.fb():d.Eb();S(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>nb(this,a)],["set-master-volume",a=>{this.Tb=a.vol;this.Na.gain.value=this.Tb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Jb(d,a)}],["set-silent",a=>{this.ua=a.isSilent;this.v.Fb(this.ua);for(const c of this.H)c.Ib()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.oc(a)}],["set-playback-rate",a=>pb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),mb(d,a)}],["seek",a=>qb(this,a)],["preload",a=>rb(this,a)],["unload",a=>sb(this,a)],["unload-all",()=>{for(const a of this.ja)a.j();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.pc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>tb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ka.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);vb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ka.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ka.delete(a);ub(this,a)}}],["tick",a=>{this.bc=a.timeScale;this.Dc=a.gameTime;this.Ed=a.tickCount;if(0!==this.Sc)for(var c of this.H)c.Da();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==
c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.pa===a&&lb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>wb(this,a)],["offline-render-audio",a=>yb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}W(){return this.g}na(){return this.Na}Cb(){return this.ua}Ca(b){this.v.Ca(b)}Ka(b){this.v.Ka(b)}Ba(){for(var b of this.Ma)b.Ba();
b=this.g.currentTime;for(var a of this.H)a.Ba(b);a=this.H.filter(c=>!c.J&&!c.O()).map(c=>c.bb());l(this,"state",{tickCount:this.Ed,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ma].map(c=>({tag:c.Qc,index:c.zd,peak:c.Ua,rms:c.Jd,binCount:c.l.frequencyBinCount,freqBins:c.vd}))});0===a.length&&0===this.Ma.size&&this.Ob&&(this.v.Fe(this.Od),this.Ob=!1)}static ne(b){return b*eb}static $c(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static le(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.gb.Ab(self.$a);"use strict";function Bb(b){b.Rb||(b.Rb=b.tc());return b.Rb}self.Xc=class{constructor(b,a,c,d,e){this.s=b;this.Ne=a;this.Ha=c;this.T=d;this.Je=e;this.yc="";this.Rb=null}j(){this.Rb=this.s=null}tc(){}W(){return this.s.W()}jc(){return this.Ne}cb(){return this.Ha}ic(){return this.T}za(){return this.Je}ga(){}};"use strict";
self.be=class extends self.Xc{constructor(b,a,c,d,e){super(b,a,c,d,e);this.yc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.qb=this.rb=null;this.M.addEventListener("canplaythrough",()=>!0);this.vb=this.W().createGain();this.tb=null;this.M.addEventListener("canplay",()=>{this.rb&&(this.rb(),this.qb=this.rb=null);!this.tb&&this.M&&(this.tb=this.W().createMediaElementSource(this.M),this.tb.connect(this.vb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ha}' error: `,f);this.qb&&(this.qb(f),this.qb=this.rb=null)})}j(){Gb(this.s,this);this.vb.disconnect();this.vb=null;this.tb.disconnect();this.tb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}tc(){return new Promise((b,a)=>{this.rb=b;this.qb=a;this.M.src=this.Ha})}V(){return this.M}ga(){return this.M.duration}};"use strict";
async function Kb(b){if(b.Ea)return b.Ea;var a=b.s.v;if("cordova"===a.B&&a.bd(b.Ha)&&a.Pb)b.Ea=await a.Bb(b.Ha);else{a=await fetch(b.Ha);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ea=await a.arrayBuffer()}}async function Lb(b){if(b.ia)return b.ia;b.ia=await Fb(b.s,b.Ea,b.Me);b.Ea=null}
self.de=class extends self.Xc{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.yc="webaudio";this.ia=this.Ea=null;this.Me=!!f}j(){Gb(this.s,this);this.ia=this.Ea=null;super.j()}async tc(){try{await Kb(this),await Lb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ha}': `,b)}}ga(){return this.ia?this.ia.duration:0}};"use strict";let Mb=0;
function P(b,a){a=!!a;b.nb!==a&&(b.nb=a,b.nb?(Q(b,!1),b.F||(b.F=b.W().createPanner(),b.F.panningModel=b.s.Hd,b.F.distanceModel=b.s.pd,b.F.refDistance=b.s.Id,b.F.maxDistance=b.s.Gd,b.F.rolloffFactor=b.s.Kd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.na())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.na())))}
function Q(b,a){a=!!a;b.Qb!==a&&(b.Qb=a,b.Qb?(P(b,!1),b.fa=b.W().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.na())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.na())))}function mb(b,a){b.Qb&&b.Pc!==a&&(b.fa.pan.value=a,b.Pc=a)}function T(b,a){b.Ia=a;b.G.gain.cancelScheduledValues(0);b.Oa=-1;b.G.gain.value=b.kc()}function Jb(b,a){a=!!a;b.Pa!==a&&(b.Pa=a,b.Ib())}
function lb(b,a,c,d,e){if(b.nb){var f=b.Ta,g=b.Sa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Kc?b.s.Dc:performance.now()/1E3}
self.Yc=class{constructor(b,a,c){this.s=b;this.P=a;this.ma=c;this.Jb=Mb++;this.G=this.W().createGain();this.G.connect(this.na());this.F=null;this.nb=!1;this.Ta=[0,0,0];this.Sa=[0,0,0];this.ra=[0,0,0];this.fa=null;this.Qb=!1;this.Pc=0;this.J=!0;this.Y=this.sa=this.K=!1;this.Ia=1;this.Pa=!1;this.la=1;b=this.s.Sc;this.Kc=1===b&&!this.za()||2===b;this.Oa=this.pa=-1;this.Md=!1}j(){this.P=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}W(){return this.s.W()}na(){return Db(this.s,0<this.ma.length?this.ma[0]:"")}jc(){return this.P.jc()}cb(){return this.P.cb()}ic(){return this.P.ic()}za(){return this.P.za()}O(){}fc(){}IsPlaying(){return!this.J&&!this.K&&!this.O()}Ja(){}ga(){return this.P.ga()}Play(){}Aa(){}fb(){}Eb(){}Ba(b){-1!==this.Oa&&b>=this.Oa&&(this.Oa=-1,this.Md&&this.Aa(),Hb(this.s,"fade-ended",this.ma,this.Jb))}kc(){const b=this.Ia;return isFinite(b)?b:0}Cb(){return this.s.Cb()}Ib(){}oc(){}Da(){}nc(){}pc(){}lc(){}bb(){var b=
this.Jb,a=this.ma,c=this.ga(),d=-1===this.Oa?this.Ia:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ta,orient:this.Sa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ja(),playbackRate:this.la,uid:this.pa,bufferOriginalUrl:this.jc(),bufferUrl:"",bufferType:this.ic(),isMusic:this.za(),isLooping:this.Y,isMuted:this.Pa,resumePosition:this.lc(),pan:f,stereoPan:this.fa?
this.Pc:null}}uc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Da());Jb(this,b.isMuted)}};"use strict";
self.ce=class extends self.Yc{constructor(b,a,c){super(b,a,c);this.P.vb.connect(this.G);this.P.onended=()=>this.vc()}j(){this.Aa();this.P.vb.disconnect();super.j()}V(){return this.P.V()}vc(){this.J=!0;this.pa=-1;Hb(this.s,"ended",this.ma,this.Jb)}O(){return this.V().ended}fc(){return this.J?!0:this.O()}Ja(){let b=this.V().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.V();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.cb()}' to position '${c}': `,e)}this.s.Ca(d);this.K=this.J=!1;this.Y=b;this.la=1}Aa(){const b=this.V();b.paused||b.pause();this.s.Ka(b);this.J=!0;this.K=!1;this.pa=-1}fb(){if(!(this.K||this.J||this.O())){var b=this.V();b.paused||b.pause();this.s.Ka(b);this.K=!0}}Eb(){!this.K||this.J||this.O()||(this.s.Ca(this.V()),this.K=!1)}Ib(){this.V().muted=this.Pa||this.Cb()}oc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.V().loop=b)}Da(){let b=this.la;this.Kc&&(b*=this.s.bc);try{this.V().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}nc(b){if(!this.J&&!this.O())try{this.V().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}lc(){return this.Ja()}pc(b){b?this.IsPlaying()?(this.V().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.s.Ca(this.V()),this.sa=!1)}};"use strict";
function V(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.hb=null}
self.ee=class extends self.Yc{constructor(b,a,c){super(b,a,c);this.o=null;this.Vb=d=>this.vc(d);this.Ec=!0;this.hb=null;this.S=this.Wb=this.Yb=0;this.Nc=1}j(){this.Aa();V(this);this.Vb=null;super.j()}vc(b){this.K||this.sa||b.target!==this.hb||(this.J=this.Ec=!0,this.pa=-1,V(this),Hb(this.s,"ended",this.ma,this.Jb))}O(){return!this.J&&this.o&&this.o.loop||this.K?!1:this.Ec}fc(){return!this.o||this.J?!0:this.O()}Ja(){let b;b=this.K?this.S:this.Wb+(U(this)-this.Yb)*this.la;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.Nc=1;T(this,a);V(this);this.o=this.W().createBufferSource();this.o.buffer=this.P.ia;this.o.connect(this.G);this.hb=this.o;this.o.onended=this.Vb;this.o.loop=b;this.o.start(d,c);this.K=this.J=this.Ec=!1;this.Y=b;this.la=1;this.Yb=U(this);this.Wb=c}Aa(){if(this.o)try{this.o.stop(0)}catch(b){}this.J=!0;this.K=!1;this.pa=-1}fb(){this.K||this.J||this.O()||(this.S=this.Ja(),this.Y&&(this.S%=this.ga()),this.K=!0,this.o.stop(0))}Eb(){!this.K||this.J||this.O()||(V(this),this.o=
this.W().createBufferSource(),this.o.buffer=this.P.ia,this.o.connect(this.G),this.hb=this.o,this.o.onended=this.Vb,this.o.loop=this.Y,T(this,this.Ia),this.Da(),this.o.start(0,this.S),this.Yb=U(this),this.Wb=this.S,this.K=!1)}kc(){return super.kc()*this.Nc}Ib(){this.Nc=this.Pa||this.Cb()?0:1;T(this,this.Ia)}oc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Da(){let b=this.la;this.Kc&&(b*=this.s.bc);this.o&&(this.o.playbackRate.value=b)}nc(b){this.J||this.O()||(this.K?this.S=b:(this.fb(),this.S=
b,this.Eb()))}lc(){return this.S}pc(b){b?this.IsPlaying()?(this.sa=!0,this.S=this.Ja(),this.Y&&(this.S%=this.ga()),this.o.stop(0)):this.sa=!1:this.sa&&(V(this),this.o=this.W().createBufferSource(),this.o.buffer=this.P.ia,this.o.connect(this.G),this.hb=this.o,this.o.onended=this.Vb,this.o.loop=this.Y,T(this,this.Ia),this.Da(),this.o.start(0,this.S),this.Yb=U(this),this.Wb=this.S,this.sa=!1)}uc(b){super.uc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.s=b;this.g=b.W();this.zd=-1;this.T=this.Qc="";this.m=null}j(){this.g=null}N(){}U(){}bb(){return{type:this.T,tag:this.Qc,params:this.m}}}
self.Vd=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.u=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i)}j(){this.u.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,X(this,this.D.gain,a,c,d)}}};
self.Td=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.u=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.sb=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.lb=W(this);this.lb.gain.value=c;this.u.connect(this.sb);this.u.connect(this.h);this.sb.connect(this.i);this.sb.connect(this.X);this.X.connect(this.lb);this.lb.connect(this.sb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.sb.disconnect();
this.X.disconnect();this.lb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){const e=self.$a.$c;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);X(this,this.lb.gain,e(a),c,d);break;case 5:this.m[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.Sd=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.od=this.nd="";this.u=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.kb=this.g.createConvolver();this.kb.normalize=c;this.kb.buffer=a;this.u.connect(this.kb);this.u.connect(this.h);this.kb.connect(this.i)}j(){this.u.disconnect();this.kb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}bb(){const b=super.bb();b.bufferOriginalUrl=this.nd;b.bufferUrl="";b.bufferType=this.od;return b}};
self.Wd=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.u=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.mb=W(this);this.mb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.L=W(this);this.L.gain.value=c;this.u.connect(this.X);this.u.connect(this.h);this.X.connect(this.i);this.X.connect(this.mb);this.mb.connect(this.X);this.A.connect(this.L);
this.L.connect(this.X.delayTime);this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.X.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.mb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;X(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;X(this,this.A.frequency,a,c,d);break;case 8:this.m[3]=a/100,X(this,this.mb.gain,a/100,c,d)}}};
self.Yd=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.u=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.L=W(this);this.L.gain.value=e;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i);this.A.connect(this.L);this.L.connect(this.D.frequency);
this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.D.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;X(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,X(this,this.A.frequency,a,c,d)}}};self.Xd=class extends Y{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.$a.$c;switch(b){case 4:this.m[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.$d=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,X(this,this.l.pan,a,c,d)}}};
self.ae=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.L=W(this);this.L.gain.value=c/2;this.A.connect(this.L);this.L.connect(this.l.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,X(this,this.A.frequency,a,c,d)}}};
self.Zd=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.u=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.xb=W(this);this.xb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.xb.gain);this.A.start(0);this.u.connect(this.xb);this.u.connect(this.h);this.xb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.xb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,X(this,this.A.frequency,a,c,d)}}};
self.Ud=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.u=W(this);this.$b=W(this);this.Zb=W(this);b=d;.01>b&&(b=.01);this.$b.gain.value=b;this.Zb.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.cc=this.g.createWaveShaper();this.Ac=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ac[32768+e]=f,this.Ac[32768-
e-1]=-f;this.cc.curve=this.Ac;this.u.connect(this.$b);this.u.connect(this.h);this.$b.connect(this.cc);this.cc.connect(this.Zb);this.Zb.connect(this.i)}j(){this.u.disconnect();this.$b.disconnect();this.cc.disconnect();this.Zb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.Rd=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.Qd=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.vd=new Float32Array(this.l.frequencyBinCount);this.Ld=new Uint8Array(a);this.Jd=this.Ua=0;b=this.s;b.Ma.add(this);S(b)}j(){this.s.Ma.delete(this);this.l.disconnect();super.j()}Ba(){this.l.getFloatFrequencyData(this.vd);this.l.getByteTimeDomainData(this.Ld);const b=this.l.fftSize;let a=this.Ua=0;for(var c=0;c<b;++c){let d=(this.Ld[c]-
128)/128;0>d&&(d=-d);this.Ua<d&&(this.Ua=d);a+=d*d}c=self.$a.le;this.Ua=c(this.Ua);this.Jd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";
self.gb.Ab(class extends self.ab{constructor(b){super(b,"mouse");t(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.v.I.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{l(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{l(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";let Nb=!1;async function Ob(b){var a=Pb(b.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:b.duration,startDelay:0,weakMagnitude:b.weakMag,strongMagnitude:b.strongMag})}catch(c){console.warn("[Gamepad] Failed to vibrate gamepad: ",c)}}function Z(){try{return Array.from(navigator.getGamepads()).filter(b=>b&&b.connected)}catch(b){return Nb||(console.warn("[Construct] Failed to access gamepads: ",b),Nb=!0),[]}}
function Pb(b){for(const a of Z())if(a.index===b)return a;return null}
self.gb.Ab(class extends self.ab{constructor(b){super(b,"gamepad");this.Bd=!!navigator.getGamepads;this.Jc=!1;p(this,"is-supported",()=>this.Bd);p(this,"ready",()=>{this.Jc=!0;for(const a of Z())l(this,"gamepad-connected",{index:a.index,id:a.id});this.Bd&&u(this)});p(this,"vibrate",a=>Ob(a));p(this,"reset-vibrate",a=>{(a=Pb(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.Jc&&(a=a.gamepad,l(this,"gamepad-connected",{index:a.index,id:a.id}))});
window.addEventListener("gamepaddisconnected",a=>{this.Jc&&l(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of Z()){const c=a.vibrationActuator;c&&c.reset&&c.reset()}})}Ba(){var b=Z();b.length&&(b=b.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(c=>({pressed:c.pressed,value:c.value})),axes:a.axes})),l(this,"input-update",b))}});
