function k(b,a,c,d){b.v.Hb(b.kb,a,c,d,void 0)}function l(b,a,c,d){b.v.ma?k(b,a,c,d):b.v.ze()._OnMessageFromDOM({type:"event",component:b.kb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.v.D(b.kb,a,c)}function aa(b,a){for(const [c,d]of a)n(b,c,d)}function t(b){b.Rb||(b.v.se(b.Qd),b.Rb=!0)}window.bb=class{constructor(b,a){this.v=b;this.kb=a;this.Rb=!1;this.Qd=()=>this.Ba()}$c(){}Ba(){}};function ba(b){-1!==b.Za&&(self.clearTimeout(b.Za),b.Za=-1)}
window.pe=class{constructor(b){this.Ec=b;this.Oe=5;this.Za=-1;this.Ub=-Infinity;this.Rd=()=>{this.Za=-1;this.Ub=Date.now();this.pb=!0;this.Ec();this.pb=!1};this.sd=this.pb=!1}j(){ba(this);this.Rd=this.Ec=null}};"use strict";function ca(b,a){n(b,"get-element",c=>{const d=b.ka.get(c.elementId);return a(d,c)})}
window.hf=class extends self.bb{constructor(b,a){super(b,a);this.ka=new Map;this.Dc=!0;aa(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=this.ka.get(c);this.Dc&&d.parentElement.removeChild(d);this.ka.delete(c)}],["set-visible",c=>{this.Dc&&(this.ka.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.Dc){var d=this.ka.get(c.elementId);d.style.left=c.left+"px";d.style.top=c.top+"px";d.style.width=c.width+"px";d.style.height=
c.height+"px";c=c.fontSize;null!==c&&(d.style.fontSize=c+"em")}}],["update-state",c=>{this.ka.get(c.elementId);throw Error("required override");}],["focus",c=>{const d=this.ka.get(c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=this.ka.get(c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{this.ka.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.ka.get(c.elementId).removeAttribute(c.name)}]]);
ca(this,c=>c)}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),u=/android/i.test(navigator.userAgent);let ea=0;function v(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Ye?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.bf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let fa=!1,ha=!1;
function ia(){if(!fa){try{new Worker("blob://",{get type(){ha=!0}})}catch(b){}fa=!0}return ha}let w=new Audio;const ja={"audio/webm; codecs=opus":!!w.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!w.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!w.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!w.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!w.canPlayType("audio/mp4"),"audio/mpeg":!!w.canPlayType("audio/mpeg")};w=null;
async function ma(b){b=await na(b);return(new TextDecoder("utf-8")).decode(b)}function na(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const y=[];let z=0;window.RealFile=window.File;const C=[],E=new Map,F=new Map;let oa=0;const pa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");pa.push(b)};const qa=new Set(["cordova","playable-ad","instant-games"]);
let ra=!1;
window.hb=class b{constructor(a){this.ma=a.df;this.va=null;this.ba="";this.Xa=a.af;this.Db={};this.Qa=this.ta=null;this.Pb=[];this.J=this.wa=null;this.Mc=!1;this.wd=0;this.rb=null;this.Wa=-1;this.Te=()=>this.Ge();this.Va=[];this.B=a.Sd;this.Sb="file"===location.protocol.substr(0,4);!this.ma||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ia()||(this.ma=!1);if("playable-ad"===this.B||"instant-games"===this.B)this.ma=!1;if("cordova"===this.B&&this.ma)if(u){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&
90<=parseInt(c[1],10)||(this.ma=!1)}else this.ma=!1;this.Wb=this.qa=null;"html5"!==this.B||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.D("runtime","cordova-fetch-local-file",c=>this.Ce(c));this.D("runtime","create-job-worker",()=>this.De());"cordova"===this.B?document.addEventListener("deviceready",()=>this.kd(a)):this.kd(a)}j(){this.uc();
this.va&&(this.va=this.va.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Qa&&(this.Qa.j(),this.Qa=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}me(){return da&&"cordova"===this.B}qc(){const a=navigator.userAgent;return da&&qa.has(this.B)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ke(){return u}ed(){return u&&qa.has(this.B)}async kd(a){"macos-wkwebview"===this.B&&this.Le();if("playable-ad"===this.B){this.qa=self.c3_base64files;this.Wb={};await this.ve();
for(let d=0,e=a.$a.length;d<e;++d){var c=a.$a[d];this.Wb.hasOwnProperty(c)?a.$a[d]={Ye:!0,bf:this.Wb[c]}:this.qa.hasOwnProperty(c)&&(a.$a[d]=URL.createObjectURL(this.qa[c]))}}a.$e?this.ba=a.$e:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.ff&&(this.Db=a.ff);c=new MessageChannel;this.va=c.port1;this.va.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>
this.Fe(d));this.rb=new self.ne(this);await sa(this.rb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ma?await this.Be(a,c.port2):await this.Ae(a,c.port2)}wc(a){a=this.Db.hasOwnProperty(a)?this.Db[a]:a.endsWith("/workermain.js")&&this.Db.hasOwnProperty("workermain.js")?this.Db["workermain.js"]:
"playable-ad"===this.B&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async lc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.B&&this.Sb)return a=await this.Fb(d.Xe?a:this.Xa+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}oa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}jd(a){var c=this.ba,d=location.href,e=this.oa(),f=this.ga(),g=window.devicePixelRatio,h=b.fb(),m=a.mf,q=window.cr_previewImageBlobs||this.qa,p=window.cr_previewProjectFileBlobs,A=window.cr_previewProjectFiles,x=window.kf||"";a=a.Sd;var r=(new URLSearchParams(self.location.search)).has("debug"),B=this.rb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,
isFullscreen:h,projectData:m,previewImageBlobs:q,previewProjectFileBlobs:p,previewProjectFileSWUrls:A,swClientId:x,exportType:a,isDebug:r,ife:!!self.lf,jobScheduler:{inputPort:B.Lc,outputPort:B.Tc,maxNumWorkers:B.Qe},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Xa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Xa+"opus.wasm.wasm",isFileProtocol:this.Sb,isiOSCordova:this.me(),isiOSWebView:this.qc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Be(a,
c){const d=this.wc(a.ef);"preview"===this.B?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const q=p=>{this.ta.removeEventListener("message",q);p.data&&"ok"===p.data.type?h():m()};this.ta.addEventListener("message",q);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,this.ba)).toString()})})):this.ta=await this.lc(d,this.ba,{type:"module",name:"Runtime",Xe:!0});this.J=document.createElement("canvas");this.J.style.display="none";
const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.Zc||[],g=a.$a;f=await Promise.all(f.map(h=>this.La(h)));g=await Promise.all(g.map(h=>this.La(h)));if("cordova"===this.B)for(let h=0,m=a.jc.length;h<m;++h){const q=a.jc[h],p=q[0];if(p===a.Xc||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))q[1]=await this.La(p)}this.ta.postMessage(Object.assign(this.jd(a),{type:"init-runtime",
isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.jc,mainProjectScript:a.Xc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ta(this.rb)]);this.Pb=C.map(h=>new h(this));this.hd();ua(this.wa);self.c3_callFunction=(h,m)=>{var q=this.wa;return q.v.gd(q.kb,"js-invoke-function",{name:h,params:m},void 0,void 0)};"preview"===this.B&&(self.goToLastErrorScript=()=>this.Hb("runtime","go-to-last-error-script"))}async Ae(a,c){this.J=document.createElement("canvas");
this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Pb=C.map(g=>new g(this));this.hd();var d=a.$a.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);Array.isArray(a.Zc)&&d.unshift(...a.Zc);d=await Promise.all(d.map(g=>this.La(g)));await Promise.all(d.map(g=>v(g)));d=self.C3_ProjectScriptsStatus;const e=a.Xc,f=a.jc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.La(h),await v(h),"preview"!==
this.B||d[g]||this.md(g,"main script did not run to completion")}catch(m){this.md(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.La(h),await v(h);"preview"===this.B&&"object"!==typeof self.gf.jf?(this.Lb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.jd(a),
{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:pa}),ua(this.wa),this.ld(),this.Qa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Qa,a))}md(a,c){this.Lb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}ld(){this.Lb()}Lb(){const a=window.Ve;a&&(a.parentElement.removeChild(a),window.Ve=null)}async De(){const a=
await va(this.rb);return{outputPort:a,transferables:[a]}}ze(){if(this.ma)throw Error("not available in worker mode");return this.Qa}Hb(a,c,d,e,f){this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}gd(a,c,d,e,f){const g=oa++,h=new Promise((m,q)=>{F.set(g,{resolve:m,reject:q})});this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ee(a);
if("result"===c)this.He(a);else if("runtime-ready"===c)this.Ie();else if("alert-error"===c)this.Lb(),alert(a.message);else if("creating-runtime"===c)this.ld();else throw Error(`unknown message '${c}'`);}Ee(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=E.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Kb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Kb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,
h);this.Kb(f,!1,""+h)}):this.Kb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Kb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.va.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}He(a){const c=a.responseId,d=a.isOk;a=a.result;const e=F.get(c);d?e.resolve(a):e.reject(a);F.delete(c)}D(a,c,d){let e=E.get(a);e||(e=new Map,E.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);
e.set(c,d)}static Eb(a){if(C.includes(a))throw Error("DOM handler already added");C.push(a)}hd(){for(const a of this.Pb)if("runtime"===a.kb){this.wa=a;return}throw Error("cannot find runtime DOM handler");}Fe(a){this.Hb("debugger","message",a)}Ie(){for(const a of this.Pb)a.$c()}static fb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ra)}static nd(a){ra=!!a}se(a){this.Va.push(a);this.Bc()}Ke(a){a=this.Va.indexOf(a);if(-1===a)throw Error("invalid callback");
this.Va.splice(a,1);this.Va.length||this.uc()}Bc(){-1===this.Wa&&this.Va.length&&(this.Wa=requestAnimationFrame(this.Te))}uc(){-1!==this.Wa&&(cancelAnimationFrame(this.Wa),this.Wa=-1)}Ge(){this.Wa=-1;for(const a of this.Va)a();this.Bc()}Ca(a){this.wa.Ca(a)}Ka(a){this.wa.Ka(a)}Ac(){this.wa.Ac()}Jb(a){this.wa.Jb(a)}le(){return!!ja["audio/webm; codecs=opus"]}async Me(a){a=await this.gd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}qe(a){this.Mc=!0;this.wd=a}je(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||
"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}fd(a){return!this.je(a)}async La(a){return"cordova"===this.B&&(a.startsWith("file:")||this.Sb&&this.fd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Fb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ce(a){const c=a.filename;switch(a.as){case "text":return await this.ie(c);case "buffer":return await this.Fb(c);default:throw Error("unsupported type");}}cd(a){const c=window.cordova.file.applicationDirectory+
"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ie(a){a=await this.cd(a);return await ma(a)}vc(){if(y.length&&!(8<=z)){z++;var a=y.shift();this.we(a.filename,a.cf,a.We)}}Fb(a){return new Promise((c,d)=>{y.push({filename:a,cf:e=>{z--;this.vc();c(e)},We:e=>{z--;this.vc();d(e)}});this.vc()})}async we(a,c,d){try{const e=await this.cd(a),f=await na(e);c(f)}catch(e){d(e)}}Le(){var a={type:"ready"};if("windows-webview2"===this.B)window.chrome.webview.postMessage(JSON.stringify(a));
else if("macos-wkwebview"===this.B)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async ve(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.ue(c,d));await Promise.all(a)}async ue(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),this.Wb[a]=c.str;else{let d=await this.ye(c);d||(d=this.xe(c));this.qa[a]=d}}async ye(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}xe(a){a=this.Je(a);return this.te(a.data,a.Ze)}Je(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Ze:a,data:d}}te(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=
3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const G=self.hb;function wa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const xa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),H={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},ya={dispatchUserScriptEvent:!0},I={dispatchRuntimeEvent:!0};
function za(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Aa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await Aa(b)}finally{URL.revokeObjectURL(b)}}
function Ba(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ca(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await Ba(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Da(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ea=new Set(["input","textarea","datalist","select"]),Fa=new Set(["canvas","body","html"]);function K(b){Fa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ga(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ca(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ha=!1;document.addEventListener("pause",()=>Ha=!0);document.addEventListener("resume",()=>Ha=!1);function ua(b){b.vd=!0;b.Qc=b.v.oa();b.sb=b.v.ga()}async function Ia(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ja(b){return await self.C3_GetSvgImageSize(b.blob)}
function Ka(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function La(b){self.setTimeout(()=>{b.ud=!0},1E3);"cordova"===b.v.B?(document.addEventListener("pause",()=>Ma(b,!0)),document.addEventListener("resume",()=>Ma(b,!1))):document.addEventListener("visibilitychange",()=>Ma(b,document.hidden));return{isSuspended:!(!document.hidden&&!Ha)}}
function Na(b){b.pd||(b.pd=!0,window.addEventListener("deviceorientation",a=>{b.Z||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},H)}),window.addEventListener("deviceorientationabsolute",a=>{b.Z||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},H)}))}
function Oa(b){b.od||(b.od=!0,window.addEventListener("devicemotion",a=>{if(!b.Z){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},H)}}))}async function Pa(b){await za(b.url)}
function Qa(b,a){b.xd=a.message;-1===b.Hc&&(b.Hc=setTimeout(()=>{b.Hc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.xd)},250))}function L(b){if(!b.Z){var a=G.fb();a&&"any"!==b.Vc&&Ra(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ga()})}}function Sa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:G.fb(),innerWidth:b.oa(),innerHeight:b.ga()})}
function Ma(b,a){a?b.v.uc():b.v.Bc();k(b,"visibilitychange",{hidden:a})}function Ta(b,a,c){"Backspace"===c.key&&K(c);if(!b.Z){var d=xa.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},H)}}
function Ua(b,a,c,d){b.Z||wa(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Va(b){window!==window.top&&window.focus();Wa(b.target)&&document.activeElement&&!Wa(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.Z){if(b.Ab&&"pointermove"!==a){var d=b.Ab;d.pb||(ba(d),d.Ub=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.xb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:(c.movementX||0)+b.cc,movementY:(c.movementY||0)+b.dc,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||
0,twist:c.twist||0,timeStamp:c.timeStamp},H);b.cc=0;b.dc=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Ua(b,d,c,ya),b.xb=c.buttons)}}
function Xa(b,a,c){if(!b.Z&&!wa(c)){var d=b.xb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},H);b.xb=c.buttons;Ua(b,c.type,c,ya)}}
function N(b,a,c){if(!b.Z)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.ca,pageX:f.pageX,pageY:f.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
H)}}function Ya(b,a,c){document.body.style.transform="";b.ca=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.ca=a))}}function Za(b,a,c,d){const e=b.oa(),f=b.ga();b.Ya=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.fb()}):10>d&&$a(b,e,f,d+1)}
function $a(b,a,c,d){-1!==b.Ya&&clearTimeout(b.Ya);b.Ya=setTimeout(()=>Za(b,a,c,d),48)}
function Ra(b){b=b.Vc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Wa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
G.Eb(class extends self.bb{constructor(b){super(b,"runtime");this.Cd=!0;this.vd=!1;this.Ya=-1;this.Vc="any";this.od=this.pd=!1;this.Fa=null;this.Z=!1;this.xd="";this.Hc=-1;this.Pa=this.Ab=null;this.dc=this.cc=0;this.ud=!1;this.Qc=b.oa();this.sb=b.ga();this.ca=this.Cb=0;b.D("canvas","update-size",d=>{var e=this.v;e.Mc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",
d.displayScale),this.Cd&&(e.style.display="",this.Cd=!1))});b.D("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.D("runtime","raster-svg-image",d=>Ia(d));b.D("runtime","get-svg-image-size",d=>Ja(d));b.D("runtime","set-target-orientation",d=>{this.Vc=d.targetOrientation});b.D("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.D("runtime",
"post-to-debugger",d=>Ka(d));b.D("runtime","go-to-script",d=>Ka(d));b.D("runtime","before-start-ticking",()=>La(this));b.D("runtime","debug-highlight",d=>{if(d.show){this.Fa||(this.Fa=document.createElement("div"),this.Fa.id="inspectOutline",document.body.appendChild(this.Fa));var e=this.Fa;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Fa&&(this.Fa.style.display="none")});b.D("runtime",
"enable-device-orientation",()=>Na(this));b.D("runtime","enable-device-motion",()=>Oa(this));b.D("runtime","add-stylesheet",d=>Pa(d));b.D("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.D("runtime","alert",d=>{alert(d.message)});b.D("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.D("runtime","set-exporting-to-video",d=>{this.Z=!0;const e=
document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.J.style.display="";this.v.qe(d.duration)});b.D("runtime","export-to-video-progress",d=>Qa(this,d));b.D("runtime","exported-to-video",d=>{window.Ue({type:"exported-video",blob:d.blob,time:d.time})});b.D("runtime","exported-to-image-sequence",d=>{window.Ue({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input",
"textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Da(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",K);window.addEventListener("touchstart",K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",
K);this.xb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ga,{passive:!1});window.addEventListener("wheel",Ga,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.Z&&this.vd){var d=this.oa();var e=this.ga();if(this.v.ed()){if(this.ud){if(this.Qc===d&&e<this.sb){this.Cb=this.sb-e;Ya(this,this.sb,this.Cb);d=void 0;break a}0<this.Cb&&(this.Cb=0,Ya(this,e,this.Cb))}this.Qc=d;this.sb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,
devicePixelRatio:window.devicePixelRatio,isFullscreen:G.fb()});this.v.qc()&&(-1!==this.Ya&&clearTimeout(this.Ya),Za(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",()=>L(this));window.addEventListener("mozfullscreenchange",()=>L(this));window.addEventListener("fullscreenerror",d=>Sa(this,d));window.addEventListener("webkitfullscreenerror",d=>Sa(this,d));window.addEventListener("mozfullscreenerror",d=>Sa(this,
d));if(b.qc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Da(f)}else d=!1}d||(document.scrollingElement.scrollTop=
0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(G.nd(!0),L(this)):"exited-fullscreen"===d?(G.nd(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Ra=new Set;this.Yb=new WeakSet;this.ua=!1}$c(){window.addEventListener("focus",()=>{k(this,"window-focus",null,I)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},I);this.xb=0});window.addEventListener("focusin",a=>{a=a.target;(Ea.has(a.tagName.toLowerCase())||
Da(a))&&k(this,"keyboard-blur",null,I)});window.addEventListener("keydown",a=>Ta(this,"keydown",a));window.addEventListener("keyup",a=>Ta(this,"keyup",a));window.addEventListener("dblclick",a=>Ua(this,"dblclick",a,H));window.addEventListener("wheel",a=>{this.Z||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.ca,pageX:a.pageX,pageY:a.pageY+this.ca,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},H)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{Va(a);M(this,"pointerdown",a)}),this.v.ma&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.Ab=new self.pe(()=>{M(this,"pointermove",this.Pa);this.Pa=null}),this.Ab.sd=!0,window.addEventListener("pointerrawupdate",a=>{this.Pa&&(this.cc+=this.Pa.movementX||0,this.dc+=this.Pa.movementY||0);this.Pa=a;a=this.Ab;if(-1===a.Za){var c=Date.now(),d=c-a.Ub,e=a.Oe;d>=e&&a.sd?(a.Ub=c,a.pb=!0,a.Ec(),a.pb=!1):a.Za=self.setTimeout(a.Rd,Math.max(e-d,4))}})):window.addEventListener("pointermove",
a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Va(a);Xa(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>Xa(this,"pointermove",a)),window.addEventListener("mouseup",a=>Xa(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Va(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",
a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=()=>this.Ac();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.ke()&&!this.v.ed()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Ya(this,this.ga(),
navigator.virtualKeyboard.boundingRect.height)}))}oa(){return this.v.oa()}ga(){return this.v.ga()}Ac(){var b=[...this.Ra];this.Ra.clear();if(!this.ua)for(const a of b)(b=a.play())&&b.catch(()=>{this.Yb.has(a)||this.Ra.add(a)})}Ca(b){if("function"!==typeof b.play)throw Error("missing play function");this.Yb.delete(b);let a;try{a=b.play()}catch(c){this.Ra.add(b);return}a&&a.catch(()=>{this.Yb.has(b)||this.Ra.add(b)})}Ka(b){this.Ra.delete(b);this.Yb.add(b)}Jb(b){this.ua=!!b}});"use strict";
async function sa(b){if(b.Ne)throw Error("already initialised");b.Ne=!0;var a=b.xa.wc(("playable-ad"===b.xa.B?b.xa.Xa:"")+"dispatchworker.js");b.Gc=await b.xa.lc(a,b.jb,{name:"DispatchWorker"});a=new MessageChannel;b.Lc=a.port1;b.Gc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Tc=await va(b)}function ta(b){return[b.Lc,b.Tc]}
async function va(b){const a=b.Ed.length;var c=b.xa.wc(("playable-ad"===b.xa.B?b.xa.Xa:"")+"jobworker.js");c=await b.xa.lc(c,b.jb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Gc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Ed.push(c);return e.port1}
self.ne=class{constructor(b){this.xa=b;this.jb=b.ba;this.jb="preview"===b.B?this.jb+"workers/":this.jb+b.Xa;this.Qe=Math.min(navigator.hardwareConcurrency||2,16);this.Gc=null;this.Ed=[];this.Tc=this.Lc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.hb({df:!0,ef:"workermain.js",$a:["scripts/c3runtime.js"],jc:[],Xc:"",af:"scripts/",Zc:[],Sd:"html5"}));"use strict";
async function cb(b,a){a=a.type;let c=!0;0===a?c=await db():1===a&&(c=await eb());k(b,"permission-result",{type:a,result:c})}async function db(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function eb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.hb.Eb(class extends self.bb{constructor(b){super(b,"touch");n(this,"request-permission",a=>cb(this,a))}});"use strict";let fb=!1;
async function gb(b){var a=ib(b.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:b.duration,startDelay:0,weakMagnitude:b.weakMag,strongMagnitude:b.strongMag})}catch(c){console.warn("[Gamepad] Failed to vibrate gamepad: ",c)}}function O(){try{return Array.from(navigator.getGamepads()).filter(b=>b&&b.connected)}catch(b){return fb||(console.warn("[Construct] Failed to access gamepads: ",b),fb=!0),[]}}
function ib(b){for(const a of O())if(a.index===b)return a;return null}
self.hb.Eb(class extends self.bb{constructor(b){super(b,"gamepad");this.Dd=!!navigator.getGamepads;this.Oc=!1;n(this,"is-supported",()=>this.Dd);n(this,"ready",()=>{this.Oc=!0;for(const a of O())k(this,"gamepad-connected",{index:a.index,id:a.id});this.Dd&&t(this)});n(this,"vibrate",a=>gb(a));n(this,"reset-vibrate",a=>{(a=ib(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.Oc&&(a=a.gamepad,k(this,"gamepad-connected",{index:a.index,id:a.id}))});
window.addEventListener("gamepaddisconnected",a=>{this.Oc&&k(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of O()){const c=a.vibrationActuator;c&&c.reset&&c.reset()}})}Ba(){var b=O();b.length&&(b=b.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(c=>({pressed:c.pressed,value:c.value})),axes:a.axes})),k(this,"input-update",b))}});"use strict";const jb=180/Math.PI;
async function kb(b,a){if(a.isiOSCordova||a.isSafari)b.ac=!0;b.Wc=a.timeScaleMode;b.Jd=["equalpower","HRTF","soundfield"][a.panningModel];b.td=["linear","inverse","exponential"][a.distanceModel];b.Kd=a.refDistance;b.Id=a.maxDistance;b.Md=a.rolloffFactor;if(b.v.Mc)b.ac=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.wd)});else{var c={latencyHint:a.latencyHint};b.Pd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");lb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&lb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Na=b.g.createGain();b.Na.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function mb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,q=a.pos,p=a.panning,A=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Fd=g;nb(b,g);try{b.$=await ob(b,c,d,e,g,f);if(p){Q(b.$,!0);var r=b.$,B=p.innerAngle,ka=p.outerAngle,la=p.outerGain;if(r.qb){pb(r,p.x,p.y,p.angle);var D=self.ab.re;r.ra[0]!==D(B)&&(r.ra[0]=D(B),
r.F.coneInnerAngle=D(B));r.ra[1]!==D(ka)&&(r.ra[1]=D(ka),r.F.coneOuterAngle=D(ka));r.ra[2]!==la&&(r.ra[2]=la,r.F.coneOuterGain=la)}p.hasOwnProperty("uid")&&(b.$.pa=p.uid)}else"number"===typeof A&&0!==A?(R(b.$,!0),qb(b.$,A)):(Q(b.$,!1),R(b.$,!1));b.$.Play(h,m,q,x)}catch(Bb){console.error("[Construct] Audio: error starting playback: ",Bb);return}finally{c=b.zb.get(g);if(!c)throw Error("expected pending tag");c.Yc--;0===c.Yc&&(c.resolve(),b.zb.delete(g))}t(b)}
async function rb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await sb(b,c);for(const p of S(b,c)){c=p;var f=d,g=e,h=a;if(!c.Oa){var m=c.G.gain;m.cancelScheduledValues(0);var q=c.s.g.currentTime;g=q+g;m.setValueAtTime(m.value,q);m.linearRampToValueAtTime(f,g);c.Ia=f;c.nb=g;c.Od=h}}T(b)}async function tb(b,a){const c=a.tag;a=a.rate;await sb(b,c);for(const d of S(b,c))b=d,b.la!==a&&(b.la=a,b.Da())}
async function ub(b,a){const c=a.tag;a=a.pos;await sb(b,c);for(const d of S(b,c))d.rc(a)}async function vb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await ob(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function wb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function xb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.Yd(b,...e);else if("delay"===c)e=new self.Wd(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Vd(b,c.ha,...e);var f=a.bufferType;c.qd=a.bufferOriginalUrl;c.rd=f}else if("flanger"===c)e=new self.Zd(b,...e);else if("phaser"===c)e=new self.ae(b,...e);else if("gain"===c)e=
new self.$d(b,...e);else if("stereopan"===c)e=new self.ce(b,...e);else if("tremolo"===c)e=new self.de(b,...e);else if("ringmod"===c)e=new self.be(b,...e);else if("distortion"===c)e=new self.Xd(b,...e);else if("compressor"===c)e=new self.Ud(b,...e);else if("analyser"===c)e=new self.Td(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.ja.get(d);e||(e=[],b.ja.set(d,e));a.Bd=e.length;a.ea=d;e.push(a);yb(b,d);zb(b)}
async function Ab(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(const e of b.I)e.za()&&1===c||!e.za()&&2===c?d.push(e):e.j();b.I=d}for(const e of b.ja.values())for(const f of e)f.j();b.ja.clear();b.hc=a.timeScale;b.Ic=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);b.ua=a.isSilent;b.v.Jb(b.ua);b.Xb=a.masterVolume;b.Na.gain.value=b.Xb;d=[];for(const e of Object.values(a.effects))d.push(Promise.all(e.map(f=>xb(b,f))));await Promise.all(d);
await Promise.all(a.playing.map(e=>Cb(b,e,c)));T(b)}async function Db(b,a){try{const c=b.g.suspend(a.time);b.Ad?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Hb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Eb(d)),b.Ad=!0);await c}catch(c){Eb(c)}}
function lb(b){b.Qb||(b.Kc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Qb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ia)if(g.eb()===c)return await Fb(g),g;if(f)return null;if(e&&(b.ac||b.zd)){f=0;for(let h=0,m=b.ia.length;h<m;++h)g=b.ia[h],b.ia[f]=g,g.za()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.Pd;e&&f&&(b.zd=!0);c=!e||b.ac||f?new self.ge(b,a,c,d,e,f):new self.ee(b,a,c,d,e);b.ia.push(c);await Fb(c);b.Hd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.Hd.add(a));return c}
function Gb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.na()}function yb(b,a){let c=b.na();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.S(b.na()):e.S(d[f+1].N())}}for(const f of S(b,a))d=c,e=f.da||f.F||f.G,e.disconnect(),e.connect(d);b.Ga&&b.Rc===a&&(b.Ga.disconnect(),b.Ga.connect(c))}
function*S(b,a){if(a)for(const c of b.I)b=c.ea,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.$&&!b.$.U()&&(yield b.$)}function Hb(b,a,c){return c?b.v.Me(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Ib(b,a){let c=0;for(let d=0,e=b.I.length;d<e;++d){const f=b.I[d];b.I[c]=f;f.O===a?f.j():++c}b.I.length=c}
async function ob(b,a,c,d,e,f){for(const g of b.I)if(g.eb()===c&&(g.kc()||f))return g.ea=e,g;a=await P(b,a,c,d,f);e="html5"===a.Cc?new self.fe(a.s,a,e):new self.he(a.s,a,e);b.I.push(e);return e}function nb(b,a){let c=b.zb.get(a);if(!c){let d=null;c={Yc:0,promise:new Promise(e=>d=e),resolve:d};b.zb.set(a,c)}c.Yc++}function sb(b,a){a||(a=b.Fd);return(b=b.zb.get(a))?b.promise:Promise.resolve()}function T(b){if(0<b.Ma.size)t(b);else for(const a of b.I)if(!a.H&&!a.U()){t(b);break}}
function Jb(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function zb(b){b.Nc||(b.Nc=!0,Promise.resolve().then(()=>Kb(b)))}function Kb(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.cb());k(b,"fxstate",{fxstate:a});b.Nc=!1}
async function Cb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,q=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await ob(b,d,e,f,h,g)}catch(A){console.error("[Construct] Audio: error loading audio state: ",A);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],f=d.orient,b.Sa[0]=f[0],b.Sa[1]=f[1],b.Sa[2]=f[2],e.setPosition(...b.Ta),e.setOrientation(...b.Sa),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),qb(b,d));c.Play(m,q,p,0);a.isPlaying||c.gb();c.yc(a)}}}function Eb(b){console.error("[Audio] Offline rendering error: ",b)}
self.ab=class extends self.bb{constructor(b){super(b,"audio");this.Na=this.g=null;this.Qb=this.Kc=!1;this.ya=()=>{if(!this.Kc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Qb&&(this.Kc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Qb=!1)}};this.ia=[];this.I=[];this.$=null;this.Fd="";this.Hd=new Set;this.Gd=-1;this.zb=new Map;this.Xb=1;this.ua=!1;this.Wc=0;this.hc=1;this.Ic=0;this.Jd="HRTF";this.td="inverse";this.Kd=600;this.Id=1E4;this.Md=1;this.aa=[0,0,0];this.zd=this.ac=!1;this.Pd=this.v.le();this.ja=new Map;this.Ma=new Set;this.Ad=this.Nc=!1;this.Rc="";this.Ga=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ga&&this.Ga.disconnect();this.Rc=c.toLowerCase();this.Ga=this.g.createMediaStreamSource(a);this.Ga.connect(Gb(this,
this.Rc))};this.Ob=null;self.C3Audio_GetOutputStream=()=>{this.Ob||(this.Ob=this.g.createMediaStreamDestination(),this.Na.connect(this.Ob));return this.Ob.stream};self.C3Audio_DOMInterface=this;aa(this,[["create-audio-context",a=>kb(this,a)],["play",a=>mb(this,a)],["stop",a=>{a=a.tag;for(const c of S(this,a))c.Aa()}],["stop-all",()=>{for(const a of this.I)a.Aa()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of S(this,c))a?d.gb():d.Ib();T(this)}],["set-volume",a=>{const c=a.tag;a=a.vol;
for(const d of S(this,c))U(d,a)}],["fade-volume",a=>rb(this,a)],["set-master-volume",a=>{this.Xb=a.vol;this.Na.gain.value=this.Xb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of S(this,c))Lb(d,a)}],["set-silent",a=>{this.ua=a.isSilent;this.v.Jb(this.ua);for(const c of this.I)c.Mb()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of S(this,c))d.sc(a)}],["set-playback-rate",a=>tb(this,a)],["set-stereo-pan",a=>{const c=a.tag;a=a.p;for(const d of S(this,c))R(d,!0),qb(d,a)}],["seek",
a=>ub(this,a)],["preload",a=>vb(this,a)],["unload",a=>wb(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.I)c.tc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>xb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.ja.get(a.tag);!a||0>c||c>=a.length||(a[c].Y(d,e,f,g),zb(this))}],["remove-effects",a=>{a=a.tag.toLowerCase();const c=
this.ja.get(a);if(c&&c.length){for(const d of c)d.j();this.ja.delete(a);yb(this,a)}}],["tick",a=>{this.hc=a.timeScale;this.Ic=a.gameTime;this.Gd=a.tickCount;if(0!==this.Wc)for(var c of this.I)c.Da();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));for(const d of a.instPans){a=d.uid;for(const e of this.I)e.pa===a&&pb(e,d.x,d.y,d.angle)}}],["load-state",a=>Ab(this,a)],["offline-render-audio",
a=>Db(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}na(){return this.Na}Gb(){return this.ua}Ca(b){this.v.Ca(b)}Ka(b){this.v.Ka(b)}Ba(){for(var b of this.Ma)b.Ba();b=this.g.currentTime;for(var a of this.I)a.Ba(b);a=this.I.filter(c=>!c.H&&!c.U()).map(c=>c.cb());k(this,"state",{tickCount:this.Gd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ma].map(c=>({tag:c.ea,index:c.Bd,peak:c.Ua,rms:c.Ld,binCount:c.l.frequencyBinCount,freqBins:c.yd}))});
0===a.length&&0===this.Ma.size&&this.Rb&&(this.v.Ke(this.Qd),this.Rb=!1)}static re(b){return b*jb}static dd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static oe(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.hb.Eb(self.ab);"use strict";function Fb(b){b.Vb||(b.Vb=b.xc());return b.Vb}self.ad=class{constructor(b,a,c,d,e){this.s=b;this.Se=a;this.Ha=c;this.R=d;this.Pe=e;this.Cc="";this.Vb=null}j(){this.Vb=this.s=null}xc(){}V(){return this.s.V()}nc(){return this.Se}eb(){return this.Ha}mc(){return this.R}za(){return this.Pe}fa(){}};
"use strict";
self.ee=class extends self.ad{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Cc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.tb=this.ub=null;this.M.addEventListener("canplaythrough",()=>!0);this.yb=this.V().createGain();this.wb=null;this.M.addEventListener("canplay",()=>{this.ub&&(this.ub(),this.tb=this.ub=null);!this.wb&&this.M&&(this.wb=this.V().createMediaElementSource(this.M),this.wb.connect(this.yb))});this.onended=null;this.M.addEventListener("ended",()=>
{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ha}' error: `,f);this.tb&&(this.tb(f),this.tb=this.ub=null)})}j(){Ib(this.s,this);this.yb.disconnect();this.yb=null;this.wb.disconnect();this.wb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}xc(){return new Promise((b,a)=>{this.ub=b;this.tb=a;this.M.src=this.Ha})}T(){return this.M}fa(){return this.M.duration}};"use strict";
async function Mb(b){if(b.Ea)return b.Ea;var a=b.s.v;if("cordova"===a.B&&a.fd(b.Ha)&&a.Sb)b.Ea=await a.Fb(b.Ha);else{a=await fetch(b.Ha);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ea=await a.arrayBuffer()}}async function Nb(b){if(b.ha)return b.ha;b.ha=await Hb(b.s,b.Ea,b.Re);b.Ea=null}
self.ge=class extends self.ad{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Cc="webaudio";this.ha=this.Ea=null;this.Re=!!f}j(){Ib(this.s,this);this.ha=this.Ea=null;super.j()}async xc(){try{await Mb(this),await Nb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ha}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Ob=0;
function Q(b,a){a=!!a;b.qb!==a&&(b.qb=a,b.qb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.s.Jd,b.F.distanceModel=b.s.td,b.F.refDistance=b.s.Kd,b.F.maxDistance=b.s.Id,b.F.rolloffFactor=b.s.Md),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.na())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.na())))}
function R(b,a){a=!!a;b.Tb!==a&&(b.Tb=a,b.Tb?(Q(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.na())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.na())))}function qb(b,a){b.Tb&&b.Uc!==a&&(b.da.pan.value=a,b.Uc=a)}function U(b,a){b.Ia=a;b.G.gain.cancelScheduledValues(0);b.nb=-1;b.G.gain.value=b.oc()}function Lb(b,a){a=!!a;b.Oa!==a&&(b.Oa=a,b.Mb())}
function pb(b,a,c,d){if(b.qb){var e=b.Ta,f=b.Sa,g=Math.cos(d);d=Math.sin(d);if(e[0]!==a||e[1]!==c||0!==e[2])e[0]=a,e[1]=c,e[2]=0,b.F.setPosition(...e);if(f[0]!==g||f[1]!==d||0!==f[2])f[0]=g,f[1]=d,f[2]=0,b.F.setOrientation(...f)}}function V(b){return b.Pc?b.s.Ic:performance.now()/1E3}
self.bd=class{constructor(b,a,c){this.s=b;this.O=a;this.ea=c;this.Nb=Ob++;this.G=this.V().createGain();this.G.connect(this.na());this.F=null;this.qb=!1;this.Ta=[0,0,0];this.Sa=[0,0,0];this.ra=[0,0,0];this.da=null;this.Tb=!1;this.Uc=0;this.H=!0;this.X=this.sa=this.K=!1;this.Ia=1;this.Oa=!1;this.la=1;b=this.s.Wc;this.Pc=1===b&&!this.za()||2===b;this.nb=this.pa=-1;this.Od=!1}j(){this.O=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.s.V()}na(){return Gb(this.s,this.ea)}nc(){return this.O.nc()}eb(){return this.O.eb()}mc(){return this.O.mc()}za(){return this.O.za()}U(){}kc(){}IsPlaying(){return!this.H&&!this.K&&!this.U()}Ja(){}fa(){return this.O.fa()}Play(){}Aa(){}gb(){}Ib(){}Ba(b){-1!==this.nb&&b>=this.nb&&(this.nb=-1,this.Od&&this.Aa(),Jb(this.s,"fade-ended",this.ea,this.Nb))}oc(){const b=this.Ia;return isFinite(b)?b:0}Gb(){return this.s.Gb()}Mb(){}sc(){}Da(){}rc(){}tc(){}pc(){}cb(){var b=this.Nb,
a=this.ea,c=this.fa(),d=this.Ia,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ta,orient:this.Sa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ja(),playbackRate:this.la,uid:this.pa,bufferOriginalUrl:this.nc(),bufferUrl:"",bufferType:this.mc(),isMusic:this.za(),isLooping:this.X,isMuted:this.Oa,resumePosition:this.pc(),pan:f,stereoPan:this.da?this.Uc:null}}yc(b){var a=b.playbackRate;
this.la!==a&&(this.la=a,this.Da());Lb(this,b.isMuted)}};"use strict";
self.fe=class extends self.bd{constructor(b,a,c){super(b,a,c);this.O.yb.connect(this.G);this.O.onended=()=>this.zc()}j(){this.Aa();this.O.yb.disconnect();super.j()}T(){return this.O.T()}zc(){this.H=!0;this.pa=-1;Jb(this.s,"ended",this.ea,this.Nb)}U(){return this.T().ended}kc(){return this.H?!0:this.U()}Ja(){let b=this.T().currentTime;this.X||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.T();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.O.eb()}' to position '${c}': `,e)}this.s.Ca(d);this.K=this.H=!1;this.X=b;this.la=1}Aa(){const b=this.T();b.paused||b.pause();this.s.Ka(b);this.H=!0;this.K=!1;this.pa=-1}gb(){if(!(this.K||this.H||this.U())){var b=this.T();b.paused||b.pause();this.s.Ka(b);this.K=!0}}Ib(){!this.K||this.H||this.U()||(this.s.Ca(this.T()),this.K=!1)}Mb(){this.T().muted=this.Oa||this.Gb()}sc(b){b=!!b;this.X!==b&&(this.X=
b,this.T().loop=b)}Da(){let b=this.la;this.Pc&&(b*=this.s.hc);try{this.T().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}rc(b){if(!this.H&&!this.U())try{this.T().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}pc(){return this.Ja()}tc(b){b?this.IsPlaying()?(this.T().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.s.Ca(this.T()),this.sa=!1)}};"use strict";function W(b){b.o&&b.o.disconnect();b.o=null;b.ib=null}
self.he=class extends self.bd{constructor(b,a,c){super(b,a,c);this.o=null;this.Zb=d=>this.zc(d);this.Jc=!0;this.ib=null;this.P=this.$b=this.bc=0;this.Sc=1}j(){this.Aa();W(this);this.Zb=null;super.j()}zc(b){this.K||this.sa||b.target!==this.ib||(this.H=this.Jc=!0,this.pa=-1,W(this),Jb(this.s,"ended",this.ea,this.Nb))}U(){return!this.H&&this.o&&this.o.loop||this.K?!1:this.Jc}kc(){return!this.o||this.H?!0:this.U()}Ja(){let b;b=this.K?this.P:this.$b+(V(this)-this.bc)*this.la;this.X||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.Sc=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.O.ha;this.o.connect(this.G);this.ib=this.o;this.o.onended=this.Zb;this.o.loop=b;this.o.start(d,c);this.K=this.H=this.Jc=!1;this.X=b;this.la=1;this.bc=V(this);this.$b=c}Aa(){if(this.o)try{this.o.stop(0)}catch(b){}this.H=!0;this.K=!1;this.pa=-1}gb(){this.K||this.H||this.U()||(this.P=this.Ja(),this.X&&(this.P%=this.fa()),this.K=!0,this.o.stop(0))}Ib(){!this.K||this.H||this.U()||(W(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.O.ha,this.o.connect(this.G),this.ib=this.o,this.o.onended=this.Zb,this.o.loop=this.X,U(this,this.Ia),this.Da(),this.o.start(0,this.P),this.bc=V(this),this.$b=this.P,this.K=!1)}oc(){return super.oc()*this.Sc}Mb(){this.Sc=this.Oa||this.Gb()?0:1;U(this,this.Ia)}sc(b){b=!!b;this.X!==b&&(this.X=b,this.o&&(this.o.loop=b))}Da(){let b=this.la;this.Pc&&(b*=this.s.hc);this.o&&(this.o.playbackRate.value=b)}rc(b){this.H||this.U()||(this.K?this.P=b:(this.gb(),this.P=
b,this.Ib()))}pc(){return this.P}tc(b){b?this.IsPlaying()?(this.sa=!0,this.P=this.Ja(),this.X&&(this.P%=this.fa()),this.o.stop(0)):this.sa=!1:this.sa&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.O.ha,this.o.connect(this.G),this.ib=this.o,this.o.onended=this.Zb,this.o.loop=this.X,U(this,this.Ia),this.Da(),this.o.start(0,this.P),this.bc=V(this),this.$b=this.P,this.sa=!1)}yc(b){super.yc(b);this.P=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.V();this.Bd=-1;this.R=this.ea="";this.m=null}j(){this.g=null}N(){}S(){}cb(){return{type:this.R,tag:this.ea,params:this.m}}}
self.Yd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="filter";this.m=[a,c,d,e,f,g];this.u=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.C=this.g.createBiquadFilter();this.C.type=a;this.C.frequency.value=c;this.C.detune.value=d;this.C.Q.value=e;this.C.gain.vlaue=f;this.u.connect(this.C);this.u.connect(this.h);this.C.connect(this.i)}j(){this.u.disconnect();this.C.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.C.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.C.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.C.gain,a,c,d)}}};
self.Wd=class extends Z{constructor(b,a,c,d){super(b);this.R="delay";this.m=[a,c,d];this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.vb=X(this);this.W=this.g.createDelay(a);this.W.delayTime.value=a;this.mb=X(this);this.mb.gain.value=c;this.u.connect(this.vb);this.u.connect(this.h);this.vb.connect(this.i);this.vb.connect(this.W);this.W.connect(this.mb);this.mb.connect(this.vb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.vb.disconnect();
this.W.disconnect();this.mb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){const e=self.ab.dd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.mb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.W.delayTime,a,c,d)}}};
self.Vd=class extends Z{constructor(b,a,c,d){super(b);this.R="convolution";this.m=[c,d];this.rd=this.qd="";this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.lb=this.g.createConvolver();this.lb.normalize=c;this.lb.buffer=a;this.u.connect(this.lb);this.u.connect(this.h);this.lb.connect(this.i)}j(){this.u.disconnect();this.lb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}cb(){const b=super.cb();b.bufferOriginalUrl=this.qd;b.bufferUrl="";b.bufferType=this.rd;return b}};
self.Zd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="flanger";this.m=[a,c,d,e,f];this.u=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.ob=X(this);this.ob.gain.value=e;this.W=this.g.createDelay(a+c);this.W.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.u.connect(this.W);this.u.connect(this.h);this.W.connect(this.i);this.W.connect(this.ob);this.ob.connect(this.W);this.A.connect(this.L);
this.L.connect(this.W.delayTime);this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.W.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.ob.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.A.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.ob.gain,a/100,c,d)}}};
self.ae=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="phaser";this.m=[a,c,d,e,f,g];this.u=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.C=this.g.createBiquadFilter();this.C.type="allpass";this.C.frequency.value=a;this.C.detune.value=c;this.C.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.u.connect(this.C);this.u.connect(this.h);this.C.connect(this.i);this.A.connect(this.L);this.L.connect(this.C.frequency);
this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.C.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.C.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.C.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.A.frequency,a,c,d)}}};self.$d=class extends Z{constructor(b,a){super(b);this.R="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){const e=self.ab.dd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.ce=class extends Z{constructor(b,a){super(b);this.R="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.de=class extends Z{constructor(b,a,c){super(b);this.R="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.A.connect(this.L);this.L.connect(this.l.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.L.disconnect();this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.be=class extends Z{constructor(b,a,c){super(b);this.R="ringmod";this.m=[a,c];this.u=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Bb=X(this);this.Bb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.Bb.gain);this.A.start(0);this.u.connect(this.Bb);this.u.connect(this.h);this.Bb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.Bb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.Xd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="distortion";this.m=[a,c,d,e,f];this.u=X(this);this.fc=X(this);this.ec=X(this);b=d;.01>b&&(b=.01);this.fc.gain.value=b;this.ec.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.ic=this.g.createWaveShaper();this.Fc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Fc[32768+e]=f,this.Fc[32768-
e-1]=-f;this.ic.curve=this.Fc;this.u.connect(this.fc);this.u.connect(this.h);this.fc.connect(this.ic);this.ic.connect(this.ec);this.ec.connect(this.i)}j(){this.u.disconnect();this.fc.disconnect();this.ic.disconnect();this.ec.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Ud=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};
self.Td=class extends Z{constructor(b,a,c){super(b);this.R="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.yd=new Float32Array(this.l.frequencyBinCount);this.Nd=new Uint8Array(a);this.Ld=this.Ua=0;b=this.s;b.Ma.add(this);T(b)}j(){this.s.Ma.delete(this);this.l.disconnect();super.j()}Ba(){this.l.getFloatFrequencyData(this.yd);this.l.getByteTimeDomainData(this.Nd);const b=this.l.fftSize;let a=this.Ua=0;for(var c=0;c<b;++c){let d=(this.Nd[c]-
128)/128;0>d&&(d=-d);this.Ua<d&&(this.Ua=d);a+=d*d}c=self.ab.oe;this.Ua=c(this.Ua);this.Ld=c(Math.sqrt(a/b))}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};
